/**
 * Free Advice Service
 * Provides pre-generated advice for FREE users without AI credits
 */

// Placeholder data structure - will be populated by generateAIDatabase script
interface AdviceResponse {
  plant: string
  issue: string
  cause: string
  solution: string
  prevention: string
  products?: string[]
  tags?: string[]
}

// This will be loaded from data/aiResponses.json
let aiResponses: Record<string, AdviceResponse> = {}

// Load responses from JSON file (will be generated by script)
export function loadAIResponses() {
  try {
    // In Next.js, we'll need to import this differently
    // For now, using a placeholder
    aiResponses = {}
  } catch (error) {
    console.error('Error loading AI responses:', error)
    aiResponses = {}
  }
}

/**
 * Get advice for a plant and issue (exact match)
 */
export function getAdvice(plant: string, issue: string): AdviceResponse | null {
  const key = `${plant.toLowerCase()}_${issue.toLowerCase().replace(/\s+/g, '-')}`
  return aiResponses[key] || null
}

/**
 * Search advice with fuzzy matching
 */
export function searchAdvice(query: {
  plant?: string
  issue?: string
  symptoms?: string[]
}): AdviceResponse[] {
  const results: Array<{ advice: AdviceResponse; score: number }> = []
  
  for (const [key, advice] of Object.entries(aiResponses)) {
    let score = 0
    
    // Match plant
    if (query.plant && advice.plant.toLowerCase().includes(query.plant.toLowerCase())) {
      score += 10
    }
    
    // Match issue
    if (query.issue && advice.issue.toLowerCase().includes(query.issue.toLowerCase())) {
      score += 10
    }
    
    // Match symptoms
    if (query.symptoms && advice.tags) {
      const symptomMatches = query.symptoms.filter(symptom =>
        advice.tags?.some(tag => tag.toLowerCase().includes(symptom.toLowerCase()))
      ).length
      score += symptomMatches * 5
    }
    
    if (score > 0) {
      results.push({ advice, score })
    }
  }
  
  // Sort by score and return top 3
  return results
    .sort((a, b) => b.score - a.score)
    .slice(0, 3)
    .map(r => r.advice)
}

/**
 * Calculate similarity score between symptoms and issue
 */
function calculateSimilarity(symptoms: string[], issue: string): number {
  const issueWords = issue.toLowerCase().split(/[-_\s]+/)
  return symptoms.filter(symptom =>
    issueWords.some(word => symptom.toLowerCase().includes(word) || word.includes(symptom.toLowerCase()))
  ).length
}

// Initialize on module load
loadAIResponses()












