/**
 * Unified Operations Service
 * Manages operations across multiple levels: Garden → Row → Plant
 * Handles automatic propagation and synchronization
 */

import {
  GardenPlant,
  PlantOperation,
  BulkRowOperation,
  BulkOperationResult
} from '../types/individualPlant';
import { autoSyncRowOperation } from './plantRowSyncService';


export interface UnifiedOperation {
  id: string;
  operationLevel: 'garden' | 'row' | 'plant';
  granularityLevel: 'garden' | 'row' | 'plant';
  operationType: 'watering' | 'fertilizing' | 'treatment' | 'pruning' | 'harvest';
  operationCategory: 'irrigation' | 'nutrition' | 'protection' | 'maintenance';

  // Context
  gardenId: string;
  gardenRowId?: string;
  fieldRowId?: string;
  plantId?: string;

  // Operation details
  operationDate: string;
  operationTimestamp: string;
  quantity?: number;
  unit?: string;
  productName?: string;
  notes?: string;

  // Metadata
  autoGenerated: boolean;
  sourceOperationId?: string;
  plantsAffected?: number;
  createdAt: string;
}

export interface OperationSyncLog {
  id: string;
  sourceType: 'watering' | 'fertilizer' | 'treatment';
  sourceOperationId: string;
  plantsAffected: number;
  operationsCreated: number;
  syncDate: string;
  syncStatus: 'pending' | 'completed' | 'failed';
  errorMessage?: string;
  gardenId: string;
}

export interface UnifiedOperationRequest {
  // Target level
  level: 'garden' | 'row' | 'plant';

  // Target identifiers
  gardenId: string;
  gardenRowId?: string;
  fieldRowId?: string;
  plantIds?: string[];

  // Operation details
  operationType: 'watering' | 'fertilizing' | 'treatment';
  operationDate: string;
  operationTime?: string;

  // Quantities and products
  quantity?: number;
  unit?: string;
  productName?: string;

  // Options
  propagateToPlants?: boolean;
  notes?: string;
}

export interface UnifiedOperationResponse {
  success: boolean;
  operationsCreated: number;
  plantsAffected: number;
  rowsAffected: number;

  // Created operation IDs
  rowOperationIds: string[];
  plantOperationIds: string[];

  // Sync information
  syncLogId?: string;
  errors?: string[];
}

/**
 * UNIFIED OPERATIONS SERVICE
 */
export class UnifiedOperationsService {
  private storageProvider: any;

  constructor(storageProvider: any) {
    this.storageProvider = storageProvider;
  }

  /**
   * Execute unified operation across multiple levels
   */
  async executeUnifiedOperation(
    request: UnifiedOperationRequest
  ): Promise<UnifiedOperationResponse> {
    try {
      const response: UnifiedOperationResponse = {
        success: false,
        operationsCreated: 0,
        plantsAffected: 0,
        rowsAffected: 0,
        rowOperationIds: [],
        plantOperationIds: [],
        errors: []
      };

      // Validate request
      const validationErrors = this.validateRequest(request);
      if (validationErrors.length > 0) {
        response.errors = validationErrors;
        return response;
      }

      // Execute based on target level
      switch (request.level) {
        case 'garden':
          return await this.executeGardenLevelOperation(request);

        case 'row':
          return await this.executeRowLevelOperation(request);

        case 'plant':
          return await this.executePlantLevelOperation(request);

        default:
          response.errors = ['Invalid operation level'];
          return response;
      }
    } catch (error) {
      console.error('Error executing unified operation:', error);
      return {
        success: false,
        operationsCreated: 0,
        plantsAffected: 0,
        rowsAffected: 0,
        rowOperationIds: [],
        plantOperationIds: [],
        errors: [error instanceof Error ? error.message : 'Unknown error']
      };
    }
  }

  /**
   * Execute garden-level operation (propagates to all rows and plants)
   */
  private async executeGardenLevelOperation(
    request: UnifiedOperationRequest
  ): Promise<UnifiedOperationResponse> {
    const response: UnifiedOperationResponse = {
      success: false,
      operationsCreated: 0,
      plantsAffected: 0,
      rowsAffected: 0,
      rowOperationIds: [],
      plantOperationIds: [],
      errors: []
    };

    try {
      // Get all rows in garden
      const [gardenRows, fieldRows] = await Promise.all([
        this.storageProvider.getGardenRows?.(request.gardenId) || [],
        this.storageProvider.getFieldRows?.(request.gardenId) || []
      ]);

      const allRows = [
        ...gardenRows.map((r: any) => ({ ...r, type: 'garden_row' })),
        ...fieldRows.map((r: any) => ({ ...r, type: 'field_row' }))
      ];

      // Execute operation for each row
      for (const row of allRows) {
        const rowRequest: UnifiedOperationRequest = {
          ...request,
          level: 'row',
          gardenRowId: row.type === 'garden_row' ? row.id : undefined,
          fieldRowId: row.type === 'field_row' ? row.id : undefined
        };

        const rowResponse = await this.executeRowLevelOperation(rowRequest);

        if (rowResponse.success) {
          response.operationsCreated += rowResponse.operationsCreated;
          response.plantsAffected += rowResponse.plantsAffected;
          response.rowsAffected += 1;
          response.rowOperationIds.push(...rowResponse.rowOperationIds);
          response.plantOperationIds.push(...rowResponse.plantOperationIds);
        } else {
          response.errors?.push(...(rowResponse.errors || []));
        }
      }

      response.success = response.operationsCreated > 0;
      return response;
    } catch (error) {
      response.errors = [error instanceof Error ? error.message : 'Garden operation failed'];
      return response;
    }
  }

  /**
   * Execute row-level operation (creates row operation and optionally propagates to plants)
   */
  private async executeRowLevelOperation(
    request: UnifiedOperationRequest
  ): Promise<UnifiedOperationResponse> {
    const response: UnifiedOperationResponse = {
      success: false,
      operationsCreated: 0,
      plantsAffected: 0,
      rowsAffected: 0,
      rowOperationIds: [],
      plantOperationIds: [],
      errors: []
    };

    try {
      let rowOperationId: string;

      // Create row-level operation based on type
      switch (request.operationType) {
        case 'watering':
          rowOperationId = await this.createWateringOperation(request);
          break;

        case 'fertilizing':
          rowOperationId = await this.createFertilizerOperation(request);
          break;

        case 'treatment':
          rowOperationId = await this.createTreatmentOperation(request);
          break;

        default:
          response.errors = ['Unsupported operation type for row level'];
          return response;
      }

      response.rowOperationIds.push(rowOperationId);
      response.operationsCreated += 1;
      response.rowsAffected += 1;

      // If propagation is enabled, trigger the precise irrigation sync
      if (request.propagateToPlants !== false) {
        // CALL PRECISE SYNC SERVICE
        try {
          console.log(`Starting precise sync for ${request.operationType} ${rowOperationId}`);

          // Map operation types if needed
          const syncOpType = request.operationType === 'fertilizing' ? 'fertilizer' : request.operationType;

          await autoSyncRowOperation(
            this.storageProvider,
            syncOpType,
            rowOperationId
          );

        } catch (syncError) {
          console.error('Error during precise sync:', syncError);
          // Don't fail the whole operation, but log it
          response.errors?.push(`Sync warning: ${syncError instanceof Error ? syncError.message : 'Unknown sync error'}`);
        }

        await new Promise(resolve => setTimeout(resolve, 100)); // Wait for any async persistence


        const syncLog = await this.getLatestSyncLog(request.operationType, rowOperationId);
        if (syncLog) {
          response.plantsAffected = syncLog.plantsAffected;
          response.operationsCreated += syncLog.operationsCreated;
          response.syncLogId = syncLog.id;

          // Get the created plant operation IDs
          const plantOperations = await this.getPlantOperationsBySource(
            request.operationType,
            rowOperationId
          );
          response.plantOperationIds = plantOperations.map(op => op.id);
        }
      }

      response.success = true;
      return response;
    } catch (error) {
      response.errors = [error instanceof Error ? error.message : 'Row operation failed'];
      return response;
    }
  }

  /**
   * Execute plant-level operation (direct plant operations)
   */
  private async executePlantLevelOperation(
    request: UnifiedOperationRequest
  ): Promise<UnifiedOperationResponse> {
    const response: UnifiedOperationResponse = {
      success: false,
      operationsCreated: 0,
      plantsAffected: 0,
      rowsAffected: 0,
      rowOperationIds: [],
      plantOperationIds: [],
      errors: []
    };

    try {
      if (!request.plantIds || request.plantIds.length === 0) {
        response.errors = ['No plants specified for plant-level operation'];
        return response;
      }

      // Create plant operations directly
      for (const plantId of request.plantIds) {
        const plantOperationId = await this.createPlantOperation({
          plantId,
          gardenId: request.gardenId,
          operationType: request.operationType,
          operationDate: request.operationDate,
          operationTime: request.operationTime,
          quantity: request.quantity,
          unit: request.unit,
          productName: request.productName,
          notes: request.notes,
          autoGenerated: false
        });

        response.plantOperationIds.push(plantOperationId);
        response.operationsCreated += 1;
        response.plantsAffected += 1;
      }

      response.success = true;
      return response;
    } catch (error) {
      response.errors = [error instanceof Error ? error.message : 'Plant operation failed'];
      return response;
    }
  }

  /**
   * Create watering operation
   */
  private async createWateringOperation(request: UnifiedOperationRequest): Promise<string> {
    const wateringLog = await this.storageProvider.createWateringLog({
      gardenId: request.gardenId,
      zoneId: '', // Not zone-based
      bedId: request.gardenRowId ? await this.getBedIdForRow(request.gardenRowId) : undefined,
      rowId: request.gardenRowId,
      fieldRowId: request.fieldRowId,
      wateredAt: `${request.operationDate}T${request.operationTime || '12:00'}:00`,
      date: request.operationDate,
      durationMinutes: 30, // Default duration
      litersApplied: request.quantity || 0,
      method: 'Manual',
      notes: request.notes,
      completed: true
    });

    return wateringLog.id;
  }

  /**
   * Create fertilizer operation
   */
  private async createFertilizerOperation(request: UnifiedOperationRequest): Promise<string> {
    if (!this.storageProvider.createFertilizerApplicationLog) {
      throw new Error('Fertilizer operations not supported by storage provider');
    }

    const fertilizerLog = await this.storageProvider.createFertilizerApplicationLog({
      gardenId: request.gardenId,
      taskId: null,
      bedId: request.gardenRowId ? await this.getBedIdForRow(request.gardenRowId) : null,
      bedRowId: request.gardenRowId || null,
      fieldRowId: request.fieldRowId || null,
      fertilizerProductId: 'manual',
      fertilizerProductName: request.productName || 'Fertilizzante generico',
      dosageAmount: request.quantity || 0,
      dosageUnit: request.unit || 'g',
      applicationDate: request.operationDate,
      method: 'surface',
      areaSqm: 1, // Will be calculated based on row
      notes: request.notes
    });

    return fertilizerLog.id;
  }

  /**
   * Create treatment operation
   */
  private async createTreatmentOperation(request: UnifiedOperationRequest): Promise<string> {
    const treatment = await this.storageProvider.createTreatment({
      garden_id: request.gardenId,
      bed_id: request.gardenRowId ? await this.getBedIdForRow(request.gardenRowId) : undefined,
      bed_row_id: request.gardenRowId,
      field_row_id: request.fieldRowId,
      crop_name: 'Coltura generica', // Could be enhanced to detect from row
      treatment_date: request.operationDate,
      product_name: request.productName || 'Prodotto generico',
      dosage: request.quantity,
      dosage_unit: request.unit || 'ml',
      method: 'spray',
      reason: 'preventive',
      notes: request.notes
    });

    return treatment.id;
  }

  /**
   * Create individual plant operation
   */
  private async createPlantOperation(params: {
    plantId: string;
    gardenId: string;
    operationType: string;
    operationDate: string;
    operationTime?: string;
    quantity?: number;
    unit?: string;
    productName?: string;
    notes?: string;
    autoGenerated: boolean;
    sourceOperationId?: string;
  }): Promise<string> {
    // This would use the plant operations storage method
    // For now, we'll simulate the ID generation
    const operationId = crypto.randomUUID();

    // In a real implementation, this would call:
    // await this.storageProvider.createPlantOperation(params);

    return operationId;
  }

  /**
   * Get unified operations for a garden with filtering
   */
  async getUnifiedOperations(
    gardenId: string,
    filters?: {
      level?: 'garden' | 'row' | 'plant';
      operationType?: string;
      dateFrom?: string;
      dateTo?: string;
      rowId?: string;
      plantId?: string;
    }
  ): Promise<UnifiedOperation[]> {
    try {
      // This would query the unified_operations view created in the migration
      // For now, return empty array as placeholder
      return [];
    } catch (error) {
      console.error('Error getting unified operations:', error);
      return [];
    }
  }

  /**
   * Get operation sync logs
   */
  async getOperationSyncLogs(
    gardenId: string,
    filters?: {
      sourceType?: string;
      syncStatus?: string;
      dateFrom?: string;
      dateTo?: string;
    }
  ): Promise<OperationSyncLog[]> {
    try {
      // This would query the operation_sync_log table
      // For now, return empty array as placeholder
      return [];
    } catch (error) {
      console.error('Error getting sync logs:', error);
      return [];
    }
  }

  /**
   * HELPER METHODS
   */

  private validateRequest(request: UnifiedOperationRequest): string[] {
    const errors: string[] = [];

    if (!request.gardenId) {
      errors.push('Garden ID is required');
    }

    if (!request.operationType) {
      errors.push('Operation type is required');
    }

    if (!request.operationDate) {
      errors.push('Operation date is required');
    }

    if (request.level === 'row' && !request.gardenRowId && !request.fieldRowId) {
      errors.push('Row ID is required for row-level operations');
    }

    if (request.level === 'plant' && (!request.plantIds || request.plantIds.length === 0)) {
      errors.push('Plant IDs are required for plant-level operations');
    }

    return errors;
  }

  private async getBedIdForRow(rowId: string): Promise<string | undefined> {
    try {
      // This would query to find the bed that contains this row
      // For now, return undefined
      return undefined;
    } catch (error) {
      console.error('Error getting bed ID for row:', error);
      return undefined;
    }
  }

  private async getLatestSyncLog(
    sourceType: string,
    sourceOperationId: string
  ): Promise<OperationSyncLog | null> {
    try {
      // This would query the operation_sync_log table
      // For now, return null
      return null;
    } catch (error) {
      console.error('Error getting sync log:', error);
      return null;
    }
  }

  private async getPlantOperationsBySource(
    sourceType: string,
    sourceOperationId: string
  ): Promise<PlantOperation[]> {
    try {
      // This would query plant_operations with source filters
      // For now, return empty array
      return [];
    } catch (error) {
      console.error('Error getting plant operations by source:', error);
      return [];
    }
  }
}

/**
 * UTILITY FUNCTIONS
 */

/**
 * Create unified operations service instance
 */
export const createUnifiedOperationsService = (storageProvider: any) => {
  return new UnifiedOperationsService(storageProvider);
};

/**
 * Execute bulk operation with unified approach
 */
export const executeBulkUnifiedOperation = async (
  storageProvider: any,
  request: UnifiedOperationRequest
): Promise<UnifiedOperationResponse> => {
  const service = createUnifiedOperationsService(storageProvider);
  return await service.executeUnifiedOperation(request);
};

/**
 * Get operation statistics for dashboard
 */
export interface OperationStatistics {
  totalOperations: number;
  operationsByType: Record<string, number>;
  operationsByLevel: Record<string, number>;
  plantsAffected: number;
  rowsAffected: number;
  autoGeneratedPercentage: number;
  recentSyncLogs: OperationSyncLog[];
}

export const getOperationStatistics = async (
  storageProvider: any,
  gardenId: string,
  dateFrom?: string,
  dateTo?: string
): Promise<OperationStatistics> => {
  try {
    const service = createUnifiedOperationsService(storageProvider);

    // Get operations and sync logs
    const [operations, syncLogs] = await Promise.all([
      service.getUnifiedOperations(gardenId, { dateFrom, dateTo }),
      service.getOperationSyncLogs(gardenId, { dateFrom, dateTo })
    ]);

    // Calculate statistics
    const operationsByType: Record<string, number> = {};
    const operationsByLevel: Record<string, number> = {};
    let autoGenerated = 0;
    const plantsAffected = new Set<string>();
    const rowsAffected = new Set<string>();

    operations.forEach(op => {
      // Count by type
      operationsByType[op.operationType] = (operationsByType[op.operationType] || 0) + 1;

      // Count by level
      operationsByLevel[op.granularityLevel] = (operationsByLevel[op.granularityLevel] || 0) + 1;

      // Count auto-generated
      if (op.autoGenerated) autoGenerated++;

      // Track affected entities
      if (op.plantId) plantsAffected.add(op.plantId);
      if (op.gardenRowId) rowsAffected.add(op.gardenRowId);
      if (op.fieldRowId) rowsAffected.add(op.fieldRowId);
    });

    return {
      totalOperations: operations.length,
      operationsByType,
      operationsByLevel,
      plantsAffected: plantsAffected.size,
      rowsAffected: rowsAffected.size,
      autoGeneratedPercentage: operations.length > 0 ? (autoGenerated / operations.length) * 100 : 0,
      recentSyncLogs: syncLogs.slice(0, 10)
    };
  } catch (error) {
    console.error('Error getting operation statistics:', error);
    return {
      totalOperations: 0,
      operationsByType: {},
      operationsByLevel: {},
      plantsAffected: 0,
      rowsAffected: 0,
      autoGeneratedPercentage: 0,
      recentSyncLogs: []
    };
  }
};

export default UnifiedOperationsService;