/**
 * Unified Operations Service
 * Manages operations across multiple levels: Garden → Row → Plant
 * Handles automatic propagation and synchronization
 */

import {
  GardenPlant,
  PlantOperation,
  BulkRowOperation,
  BulkOperationResult
} from '../types/individualPlant';
import { autoSyncRowOperation } from './plantRowSyncService';
import { createControlledEnvironmentExecutionService } from './controlledEnvironmentExecutionService';
import { appendSourceTaskReference } from './taskExecutionTraceService';
import type {
  ControlledEnvironmentExecutionMode,
  ControlledEnvironmentOperationType,
  SolutionSnapshot,
} from '../types/controlledEnvironment';
import type { IStorageProvider } from '@/packages/core/storage/interface';


export interface UnifiedOperation {
  id: string;
  operationLevel: 'garden' | 'row' | 'plant';
  granularityLevel: 'garden' | 'row' | 'plant';
  operationType:
    | 'watering'
    | 'fertilizing'
    | 'treatment'
    | 'work'
    | 'pruning'
    | 'harvest'
    | ControlledEnvironmentOperationType;
  operationCategory: 'irrigation' | 'nutrition' | 'protection' | 'maintenance';
  executionMode?: ControlledEnvironmentExecutionMode;

  // Context
  gardenId: string;
  gardenRowId?: string;
  fieldRowId?: string;
  plantId?: string;
  environmentProfileId?: string;
  reservoirId?: string;
  loopId?: string;
  growSiteIds?: string[];

  // Operation details
  operationDate: string;
  operationTimestamp: string;
  quantity?: number;
  unit?: string;
  productName?: string;
  notes?: string;
  sourceTaskId?: string;

  // Metadata
  autoGenerated: boolean;
  sourceOperationId?: string;
  plantsAffected?: number;
  createdAt: string;
}

export interface OperationSyncLog {
  id: string;
  sourceType: 'watering' | 'fertilizer' | 'treatment';
  sourceOperationId: string;
  plantsAffected: number;
  operationsCreated: number;
  syncDate: string;
  syncStatus: 'pending' | 'completed' | 'failed';
  errorMessage?: string;
  gardenId: string;
}

export interface UnifiedOperationRequest {
  // Target level
  level: 'garden' | 'row' | 'plant';
  executionMode?: ControlledEnvironmentExecutionMode;

  // Target identifiers
  gardenId: string;
  gardenRowId?: string;
  fieldRowId?: string;
  plantIds?: string[];
  environmentProfileId?: string;
  reservoirId?: string;
  loopId?: string;
  growSiteIds?: string[];

  // Operation details
  operationType:
    | 'watering'
    | 'fertilizing'
    | 'treatment'
    | 'work'
    | ControlledEnvironmentOperationType;
  operationDate: string;
  operationTime?: string;

  // Quantities and products
  quantity?: number;
  unit?: string;
  productName?: string;
  durationMinutes?: number;
  method?: string;
  areaSqm?: number;
  solutionSnapshot?: SolutionSnapshot;
  waterAddedLiters?: number;
  solutionRemovedLiters?: number;
  nutrientProductId?: string;
  nutrientDoseAmount?: number;
  nutrientDoseUnit?: string;
  phAdjusterProductId?: string;
  phAdjusterAmount?: number;
  bufferAdded?: string;
  fishFeedType?: string;
  fishFeedAmountGrams?: number;

  // Options
  propagateToPlants?: boolean;
  notes?: string;
  sourceTaskId?: string;
  sourceType?: 'manual' | 'iot' | 'orchestrator_auto' | 'orchestrator_sync';
  actorType?: 'manual' | 'iot' | 'orchestrator';
  deviceId?: string;
  contextSnapshot?: PlantOperation['context'];
  weatherConditions?: PlantOperation['weatherConditions'];
  geoSnapshot?: PlantOperation['geoSnapshot'];
}

export interface UnifiedOperationResponse {
  success: boolean;
  operationsCreated: number;
  plantsAffected: number;
  rowsAffected: number;

  // Created operation IDs
  rowOperationIds: string[];
  plantOperationIds: string[];
  controlledEnvironmentExecutionIds?: string[];

  // Sync information
  syncLogId?: string;
  errors?: string[];
}

function normalizeDosageUnit(unit: string | undefined): 'g' | 'ml' | 'kg' | 'L' {
  const valid = ['g', 'ml', 'kg', 'L'] as const;
  return valid.includes(unit as 'g') ? (unit as 'g' | 'ml' | 'kg' | 'L') : 'ml';
}

/**
 * UNIFIED OPERATIONS SERVICE
 */
export class UnifiedOperationsService {
  private storageProvider: IStorageProvider;

  constructor(storageProvider: IStorageProvider) {
    this.storageProvider = storageProvider;
  }

  /**
   * Execute unified operation across multiple levels
   */
  async executeUnifiedOperation(
    request: UnifiedOperationRequest
  ): Promise<UnifiedOperationResponse> {
    try {
      const response: UnifiedOperationResponse = {
        success: false,
        operationsCreated: 0,
        plantsAffected: 0,
        rowsAffected: 0,
        rowOperationIds: [],
        plantOperationIds: [],
        errors: []
      };

      // Validate request
      const validationErrors = this.validateRequest(request);
      if (validationErrors.length > 0) {
        response.errors = validationErrors;
        return response;
      }

      if (request.executionMode === 'recirculating') {
        return await this.executeRecirculatingOperation(request);
      }

      // Execute based on target level
      switch (request.level) {
        case 'garden':
          return await this.executeGardenLevelOperation(request);

        case 'row':
          return await this.executeRowLevelOperation(request);

        case 'plant':
          return await this.executePlantLevelOperation(request);

        default:
          response.errors = ['Invalid operation level'];
          return response;
      }
    } catch (error) {
      console.error('Error executing unified operation:', error);
      return {
        success: false,
        operationsCreated: 0,
        plantsAffected: 0,
        rowsAffected: 0,
        rowOperationIds: [],
        plantOperationIds: [],
        errors: [error instanceof Error ? error.message : 'Unknown error']
      };
    }
  }

  private async executeRecirculatingOperation(
    request: UnifiedOperationRequest
  ): Promise<UnifiedOperationResponse> {
    const response: UnifiedOperationResponse = {
      success: false,
      operationsCreated: 0,
      plantsAffected: request.plantIds?.length || 0,
      rowsAffected: 0,
      rowOperationIds: [],
      plantOperationIds: [],
      controlledEnvironmentExecutionIds: [],
      errors: []
    };

    try {
      const executionService = createControlledEnvironmentExecutionService(this.storageProvider);
      const created = await executionService.createExecution({
        gardenId: request.gardenId,
        environmentProfileId: request.environmentProfileId || `ce-env-${request.gardenId}`,
        reservoirId: request.reservoirId,
        loopId: request.loopId,
        growSiteIds: request.growSiteIds,
        plantIds: request.plantIds,
        executionMode: 'recirculating',
        operationType: request.operationType as ControlledEnvironmentOperationType,
        operationDate: request.operationDate,
        operationTime: request.operationTime,
        sourceType: request.sourceType || 'manual',
        actorType: request.actorType
          || (request.sourceType === 'iot'
            ? 'iot'
            : request.sourceType === 'manual'
              ? 'manual'
              : 'orchestrator'),
        notes: request.notes,
        solutionSnapshot: request.solutionSnapshot,
        waterAddedLiters: request.waterAddedLiters
          ?? (request.operationType === 'solution_top_up' ? request.quantity : undefined),
        solutionRemovedLiters: request.solutionRemovedLiters,
        nutrientProductId: request.nutrientProductId,
        nutrientProductName: request.productName,
        nutrientDoseAmount: request.nutrientDoseAmount ?? request.quantity,
        nutrientDoseUnit: request.nutrientDoseUnit ?? request.unit,
        phAdjusterProductId: request.phAdjusterProductId,
        phAdjusterAmount: request.phAdjusterAmount,
        bufferAdded: request.bufferAdded,
        fishFeedType: request.fishFeedType || request.productName,
        fishFeedAmountGrams: request.fishFeedAmountGrams
          ?? (request.operationType === 'fish_feed' ? request.quantity : undefined),
      });

      response.success = true;
      response.operationsCreated = 1;
      response.controlledEnvironmentExecutionIds = [created.id];
      return response;
    } catch (error) {
      response.errors = [error instanceof Error ? error.message : 'Recirculating operation failed'];
      return response;
    }
  }

  /**
   * Execute garden-level operation (propagates to all rows and plants)
   */
  private async executeGardenLevelOperation(
    request: UnifiedOperationRequest
  ): Promise<UnifiedOperationResponse> {
    const response: UnifiedOperationResponse = {
      success: false,
      operationsCreated: 0,
      plantsAffected: 0,
      rowsAffected: 0,
      rowOperationIds: [],
      plantOperationIds: [],
      errors: []
    };

    try {
      // Get all rows in garden
      const [gardenRows, fieldRows] = await Promise.all([
        this.storageProvider.getGardenRows?.(request.gardenId) || [],
        this.storageProvider.getFieldRows?.(request.gardenId) || []
      ]);

      const allRows = [
        ...gardenRows.map((r: any) => ({ ...r, type: 'garden_row' })),
        ...fieldRows.map((r: any) => ({ ...r, type: 'field_row' }))
      ];

      // Execute operation for each row
      for (const row of allRows) {
        const rowRequest: UnifiedOperationRequest = {
          ...request,
          level: 'row',
          gardenRowId: row.type === 'garden_row' ? row.id : undefined,
          fieldRowId: row.type === 'field_row' ? row.id : undefined
        };

        const rowResponse = await this.executeRowLevelOperation(rowRequest);

        if (rowResponse.success) {
          response.operationsCreated += rowResponse.operationsCreated;
          response.plantsAffected += rowResponse.plantsAffected;
          response.rowsAffected += 1;
          response.rowOperationIds.push(...rowResponse.rowOperationIds);
          response.plantOperationIds.push(...rowResponse.plantOperationIds);
        } else {
          response.errors?.push(...(rowResponse.errors || []));
        }
      }

      response.success = response.operationsCreated > 0;
      return response;
    } catch (error) {
      response.errors = [error instanceof Error ? error.message : 'Garden operation failed'];
      return response;
    }
  }

  /**
   * Execute row-level operation (creates row operation and optionally propagates to plants)
   */
  private async executeRowLevelOperation(
    request: UnifiedOperationRequest
  ): Promise<UnifiedOperationResponse> {
    const response: UnifiedOperationResponse = {
      success: false,
      operationsCreated: 0,
      plantsAffected: 0,
      rowsAffected: 0,
      rowOperationIds: [],
      plantOperationIds: [],
      errors: []
    };

    try {
      let rowOperationId: string;

      // Create row-level operation based on type
      switch (request.operationType) {
        case 'watering':
          rowOperationId = await this.createWateringOperation(request);
          break;

        case 'fertilizing':
          rowOperationId = await this.createFertilizerOperation(request);
          break;

        case 'treatment':
          rowOperationId = await this.createTreatmentOperation(request);
          break;

        case 'work':
          rowOperationId = await this.createWorkOperation(request);
          break;

        default:
          response.errors = ['Unsupported operation type for row level'];
          return response;
      }

      response.rowOperationIds.push(rowOperationId);
      response.operationsCreated += 1;
      response.rowsAffected += 1;

      // If propagation is enabled, trigger the precise irrigation sync
      if (request.propagateToPlants !== false && request.operationType !== 'work') {
        // CALL PRECISE SYNC SERVICE
        try {
          console.log(`Starting precise sync for ${request.operationType} ${rowOperationId}`);

          // Map operation types if needed
          const syncOpType = request.operationType === 'fertilizing' ? 'fertilizer' : request.operationType;

          const syncResult = await autoSyncRowOperation(
            this.storageProvider,
            syncOpType,
            rowOperationId
          );

          if (syncResult.success) {
            response.plantsAffected = syncResult.plantsAffected;
            response.operationsCreated += syncResult.operationsProcessed;
            response.plantOperationIds = syncResult.plantOperationIds || [];
          } else if (syncResult.errors.length > 0) {
            response.errors?.push(...syncResult.errors);
          }

        } catch (syncError) {
          console.error('Error during precise sync:', syncError);
          // Don't fail the whole operation, but log it
          response.errors?.push(`Sync warning: ${syncError instanceof Error ? syncError.message : 'Unknown sync error'}`);
        }
      }

      response.success = true;
      return response;
    } catch (error) {
      response.errors = [error instanceof Error ? error.message : 'Row operation failed'];
      return response;
    }
  }

  /**
   * Execute plant-level operation (direct plant operations)
   */
  private async executePlantLevelOperation(
    request: UnifiedOperationRequest
  ): Promise<UnifiedOperationResponse> {
    const response: UnifiedOperationResponse = {
      success: false,
      operationsCreated: 0,
      plantsAffected: 0,
      rowsAffected: 0,
      rowOperationIds: [],
      plantOperationIds: [],
      errors: []
    };

    try {
      if (!request.plantIds || request.plantIds.length === 0) {
        response.errors = ['No plants specified for plant-level operation'];
        return response;
      }

      // Create plant operations directly
      for (const plantId of request.plantIds) {
        const plantOperationId = await this.createPlantOperation({
          plantId,
          gardenId: request.gardenId,
          gardenRowId: request.gardenRowId,
          fieldRowId: request.fieldRowId,
          operationType: request.operationType,
          operationDate: request.operationDate,
          operationTime: request.operationTime,
          quantity: request.quantity,
          unit: request.unit,
          productName: request.productName,
          notes: request.notes,
          sourceTaskId: request.sourceTaskId,
          sourceType: request.sourceType || 'manual',
          actorType: request.actorType
            || (request.sourceType === 'iot'
              ? 'iot'
              : request.sourceType === 'manual'
                ? 'manual'
                : 'orchestrator'),
          deviceId: request.deviceId,
          contextSnapshot: request.contextSnapshot,
          weatherConditions: request.weatherConditions,
          geoSnapshot: request.geoSnapshot,
          autoGenerated: false
        });

        response.plantOperationIds.push(plantOperationId);
        response.operationsCreated += 1;
        response.plantsAffected += 1;
      }

      response.success = true;
      return response;
    } catch (error) {
      response.errors = [error instanceof Error ? error.message : 'Plant operation failed'];
      return response;
    }
  }

  /**
   * Create watering operation
   */
  private async createWateringOperation(request: UnifiedOperationRequest): Promise<string> {
    const wateringMethod = request.method === 'Automatic' || request.method === 'Timer'
      ? request.method
      : 'Manual';

    const wateringLog = await this.storageProvider.createWateringLog({
      gardenId: request.gardenId,
      zoneId: undefined, // Not zone-based
      bedId: request.gardenRowId ? await this.getBedIdForRow(request.gardenRowId) : undefined,
      rowId: request.gardenRowId,
      fieldRowId: request.fieldRowId,
      wateredAt: `${request.operationDate}T${request.operationTime || '12:00'}:00`,
      date: request.operationDate,
      durationMinutes: request.durationMinutes ?? 30,
      litersApplied: request.quantity || 0,
      method: wateringMethod,
      weatherCondition: typeof request.weatherConditions?.condition === 'string'
        ? request.weatherConditions.condition
        : undefined,
      airTemperatureC: this.parseWeatherTemperature(request.weatherConditions),
      notes: request.sourceTaskId
        ? appendSourceTaskReference(request.notes, request.sourceTaskId)
        : request.notes,
      completed: true
    });

    return wateringLog.id;
  }

  /**
   * Create fertilizer operation
   */
  private async createFertilizerOperation(request: UnifiedOperationRequest): Promise<string> {
    if (!this.storageProvider.createFertilizerApplicationLog) {
      throw new Error('Fertilizer operations not supported by storage provider');
    }

    const fertilizerLog = await this.storageProvider.createFertilizerApplicationLog({
      gardenId: request.gardenId,
      taskId: request.sourceTaskId || null,
      bedId: request.gardenRowId ? await this.getBedIdForRow(request.gardenRowId) : null,
      bedRowId: request.gardenRowId || null,
      fieldRowId: request.fieldRowId || null,
      fertilizerProductId: 'manual',
      fertilizerProductName: request.productName || 'Fertilizzante generico',
      dosageAmount: request.quantity || 0,
      dosageUnit: request.unit || 'g',
      applicationDate: request.operationDate,
      method: request.method === 'incorporated' || request.method === 'fertigation' || request.method === 'foliar'
        ? request.method
        : 'surface',
      areaSqm: request.areaSqm ?? 1,
      weatherConditions: request.weatherConditions || null,
      notes: request.sourceTaskId
        ? appendSourceTaskReference(request.notes, request.sourceTaskId)
        : request.notes
    });

    return fertilizerLog.id;
  }

  /**
   * Create treatment operation
   */
  private async createTreatmentOperation(request: UnifiedOperationRequest): Promise<string> {
    const treatment = await this.storageProvider.createTreatment({
      garden_id: request.gardenId,
      task_id: request.sourceTaskId || null,
      bed_id: request.gardenRowId ? await this.getBedIdForRow(request.gardenRowId) : undefined,
      bed_row_id: request.gardenRowId,
      field_row_id: request.fieldRowId,
      crop_name: 'Coltura generica', // Could be enhanced to detect from row
      treatment_date: request.operationDate,
      product_name: request.productName || 'Prodotto generico',
      dosage: request.quantity,
      dosage_unit: normalizeDosageUnit(request.unit),
      method: 'spray',
      reason: 'preventive',
      weather_conditions: request.weatherConditions || undefined,
      notes: request.sourceTaskId
        ? appendSourceTaskReference(request.notes, request.sourceTaskId)
        : request.notes
    });

    return treatment.id;
  }

  /**
   * Create mechanical work operation
   */
  private async createWorkOperation(request: UnifiedOperationRequest): Promise<string> {
    if (!this.storageProvider.createMechanicalWork) {
      throw new Error('Work operations not supported by storage provider');
    }

    const work = await this.storageProvider.createMechanicalWork({
      garden_id: request.gardenId,
      task_id: request.sourceTaskId || null,
      bed_id: request.gardenRowId ? await this.getBedIdForRow(request.gardenRowId) : undefined,
      bed_row_id: request.gardenRowId,
      field_row_id: request.fieldRowId,
      work_type: 'Tilling',
      work_date: request.operationDate,
      area_m2: 1,
      equipment_type: 'Manual',
      weather_conditions: request.weatherConditions || undefined,
      notes: request.sourceTaskId
        ? appendSourceTaskReference(request.notes, request.sourceTaskId)
        : request.notes
    });

    return work.id;
  }

  /**
   * Create individual plant operation
   */
  private async createPlantOperation(params: {
    plantId: string;
    gardenId: string;
    gardenRowId?: string;
    fieldRowId?: string;
    operationType: string;
    operationDate: string;
    operationTime?: string;
    quantity?: number;
    unit?: string;
    productName?: string;
    notes?: string;
    sourceTaskId?: string;
    sourceType?: 'manual' | 'iot' | 'orchestrator_auto' | 'orchestrator_sync';
    actorType?: 'manual' | 'iot' | 'orchestrator';
    deviceId?: string;
    contextSnapshot?: PlantOperation['context'];
    weatherConditions?: PlantOperation['weatherConditions'];
    geoSnapshot?: PlantOperation['geoSnapshot'];
    autoGenerated: boolean;
    sourceOperationId?: string;
  }): Promise<string> {
    if (!this.storageProvider.createPlantOperation) {
      throw new Error('Plant operations not supported by storage provider');
    }

    const created = await this.storageProvider.createPlantOperation({
      gardenId: params.gardenId,
      plantId: params.plantId,
      gardenRowId: params.gardenRowId,
      fieldRowId: params.fieldRowId,
      operationType: params.operationType,
      operationDate: params.operationDate,
      operationTime: params.operationTime,
      quantity: params.quantity,
      unit: params.unit,
      productName: params.productName,
      context: params.contextSnapshot,
      operationContext: params.contextSnapshot,
      weatherConditions: params.weatherConditions,
      geoSnapshot: params.geoSnapshot,
      notes: params.sourceTaskId
        ? appendSourceTaskReference(params.notes, params.sourceTaskId)
        : params.notes,
      parentOperationId: params.sourceOperationId,
      parentOperationTable: params.autoGenerated
        ? 'orchestrator_auto'
        : (params.sourceType === 'iot' ? 'iot_sensor' : 'manual_orchestrator'),
      sourceType: params.autoGenerated
        ? 'orchestrator_auto'
        : params.sourceType,
      actorType: params.actorType
        || (params.sourceType === 'iot'
          ? 'iot'
          : params.sourceType === 'manual'
            ? 'manual'
            : 'orchestrator'),
      deviceId: params.deviceId
    });

    return created.id;
  }

  /**
   * Get unified operations for a garden with filtering
   */
  async getUnifiedOperations(
    gardenId: string,
    filters?: {
      level?: 'garden' | 'row' | 'plant';
      operationType?: string;
      dateFrom?: string;
      dateTo?: string;
      rowId?: string;
      plantId?: string;
    }
  ): Promise<UnifiedOperation[]> {
    try {
      const [wateringLogs, fertilizerLogs, treatmentLogs, mechanicalWorks] = await Promise.all([
        this.readWateringLogs(gardenId, filters),
        this.readFertilizerLogs(gardenId, filters),
        this.readTreatmentLogs(gardenId, filters),
        this.readMechanicalWorks(gardenId, filters),
      ]);

      const plantOperations = await this.readPlantOperations(gardenId, filters);

      const all = [
        ...wateringLogs,
        ...fertilizerLogs,
        ...treatmentLogs,
        ...mechanicalWorks,
        ...plantOperations,
      ];

      return all
        .filter((item) => this.matchesUnifiedFilters(item, filters))
        .sort((a, b) => new Date(b.operationTimestamp).getTime() - new Date(a.operationTimestamp).getTime());
    } catch (error) {
      console.error('Error getting unified operations:', error);
      return [];
    }
  }

  /**
   * Get operation sync logs
   */
  async getOperationSyncLogs(
    gardenId: string,
    filters?: {
      sourceType?: string;
      syncStatus?: string;
      dateFrom?: string;
      dateTo?: string;
    }
  ): Promise<OperationSyncLog[]> {
    try {
      const operations = await this.getUnifiedOperations(gardenId, {
        dateFrom: filters?.dateFrom,
        dateTo: filters?.dateTo,
      });

      const syncCandidates = operations.filter((operation) =>
        operation.autoGenerated ||
        operation.sourceOperationId ||
        operation.notes?.includes('SOURCE_TASK:')
      );

      const grouped = new Map<string, OperationSyncLog>();

      for (const op of syncCandidates) {
        const sourceType = this.detectSyncSourceType(op);
        const status: OperationSyncLog['syncStatus'] = op.autoGenerated ? 'completed' : 'pending';
        const key = `${sourceType}:${op.sourceOperationId || op.id}:${op.operationDate}`;
        const existing = grouped.get(key);

        if (existing) {
          existing.operationsCreated += 1;
          existing.plantsAffected += op.plantsAffected || 0;
          continue;
        }

        grouped.set(key, {
          id: `sync:${key}`,
          sourceType,
          sourceOperationId: op.sourceOperationId || op.id,
          plantsAffected: op.plantsAffected || 0,
          operationsCreated: 1,
          syncDate: op.operationDate,
          syncStatus: status,
          gardenId,
        });
      }

      let logs = Array.from(grouped.values());
      if (filters?.sourceType) {
        logs = logs.filter((log) => log.sourceType === filters.sourceType);
      }
      if (filters?.syncStatus) {
        logs = logs.filter((log) => log.syncStatus === filters.syncStatus);
      }

      return logs.sort((a, b) => new Date(b.syncDate).getTime() - new Date(a.syncDate).getTime());
    } catch (error) {
      console.error('Error getting sync logs:', error);
      return [];
    }
  }

  /**
   * HELPER METHODS
   */

  private validateRequest(request: UnifiedOperationRequest): string[] {
    const errors: string[] = [];

    if (!request.gardenId) {
      errors.push('Garden ID is required');
    }

    if (!request.operationType) {
      errors.push('Operation type is required');
    }

    if (!request.operationDate) {
      errors.push('Operation date is required');
    }

    if (request.level === 'row' && !request.gardenRowId && !request.fieldRowId) {
      if (request.executionMode !== 'recirculating') {
      errors.push('Row ID is required for row-level operations');
      }
    }

    if (request.level === 'plant' && (!request.plantIds || request.plantIds.length === 0)) {
      errors.push('Plant IDs are required for plant-level operations');
    }

    return errors;
  }

  private resolveTimestamp(operationDate?: string, operationTime?: string): string {
    if (!operationDate) {
      return new Date().toISOString();
    }
    if (operationDate.includes('T')) {
      return operationDate;
    }
    if (!operationTime) {
      return `${operationDate}T00:00:00.000Z`;
    }
    return `${operationDate}T${operationTime}:00.000Z`;
  }

  private asUnifiedOperation(input: {
    id: string;
    level: UnifiedOperation['operationLevel'];
    type: UnifiedOperation['operationType'];
    gardenId: string;
    operationDate?: string;
    operationTime?: string;
    quantity?: number;
    unit?: string;
    productName?: string;
    notes?: string;
    gardenRowId?: string;
    fieldRowId?: string;
    plantId?: string;
    sourceOperationId?: string;
    autoGenerated?: boolean;
    plantsAffected?: number;
  }): UnifiedOperation {
    const operationDate = input.operationDate || new Date().toISOString().split('T')[0];
    return {
      id: input.id,
      operationLevel: input.level,
      granularityLevel: input.level,
      operationType: input.type,
      operationCategory: this.getUnifiedOperationCategory(input.type),
      gardenId: input.gardenId,
      gardenRowId: input.gardenRowId,
      fieldRowId: input.fieldRowId,
      plantId: input.plantId,
      operationDate,
      operationTimestamp: this.resolveTimestamp(operationDate, input.operationTime),
      quantity: input.quantity,
      unit: input.unit,
      productName: input.productName,
      notes: input.notes,
      autoGenerated: Boolean(input.autoGenerated),
      sourceOperationId: input.sourceOperationId,
      plantsAffected: input.plantsAffected,
      createdAt: this.resolveTimestamp(operationDate, input.operationTime),
    };
  }

  private getUnifiedOperationCategory(type: UnifiedOperation['operationType']): UnifiedOperation['operationCategory'] {
    switch (type) {
      case 'watering':
        return 'irrigation';
      case 'fertilizing':
        return 'nutrition';
      case 'treatment':
        return 'protection';
      default:
        return 'maintenance';
    }
  }

  private async readWateringLogs(
    gardenId: string,
    filters?: { dateFrom?: string; dateTo?: string }
  ): Promise<UnifiedOperation[]> {
    if (!this.storageProvider.getWateringLogs) return [];
    const logs = await this.storageProvider.getWateringLogs(undefined, gardenId, {
      from: filters?.dateFrom || '',
      to: filters?.dateTo || '',
    });

    return (logs || []).map((log: any) =>
      this.asUnifiedOperation({
        id: `watering:${log.id}`,
        level: log.fieldRowId || log.rowId || log.gardenRowId ? 'row' : 'garden',
        type: 'watering',
        gardenId,
        operationDate: log.date || log.wateringDate || log.createdAt,
        quantity: log.amount || log.quantity || log.waterAmount,
        unit: log.unit || 'L',
        notes: log.notes,
        fieldRowId: log.fieldRowId || log.rowId,
        gardenRowId: log.gardenRowId,
        sourceOperationId: log.id,
      })
    );
  }

  private async readFertilizerLogs(
    gardenId: string,
    filters?: { dateFrom?: string; dateTo?: string }
  ): Promise<UnifiedOperation[]> {
    if (!this.storageProvider.getFertilizerApplicationLogs) return [];
    const logs = await this.storageProvider.getFertilizerApplicationLogs(gardenId, {
      from: filters?.dateFrom,
      to: filters?.dateTo,
    });

    return (logs || []).map((log: any) =>
      this.asUnifiedOperation({
        id: `fertilizer:${log.id}`,
        level: log.fieldRowId || log.rowId || log.bedRowId ? 'row' : 'garden',
        type: 'fertilizing',
        gardenId,
        operationDate: log.applicationDate || log.application_date || log.createdAt || log.created_at,
        quantity: log.quantity || log.amount,
        unit: log.unit || 'g',
        productName: log.productName || log.fertilizerProductName,
        notes: log.notes,
        fieldRowId: log.fieldRowId || log.rowId || log.bedRowId,
        sourceOperationId: log.id,
      })
    );
  }

  private async readTreatmentLogs(
    gardenId: string,
    filters?: { dateFrom?: string; dateTo?: string }
  ): Promise<UnifiedOperation[]> {
    if (!this.storageProvider.getTreatments) return [];
    const logs = await this.storageProvider.getTreatments(gardenId);

    return (logs || []).map((log: any) =>
      this.asUnifiedOperation({
        id: `treatment:${log.id}`,
        level: log.fieldRowId || log.row_id || log.bed_row_id ? 'row' : 'garden',
        type: 'treatment',
        gardenId,
        operationDate: log.treatment_date || log.date || log.created_at,
        quantity: log.dosage || log.quantity,
        unit: log.dosage_unit || log.unit || 'ml',
        productName: log.product_name || log.productName,
        notes: log.notes,
        fieldRowId: log.fieldRowId || log.row_id || log.bed_row_id,
        sourceOperationId: log.id,
      })
    ).filter((item: UnifiedOperation) => {
      if (filters?.dateFrom && item.operationDate < filters.dateFrom) return false;
      if (filters?.dateTo && item.operationDate > filters.dateTo) return false;
      return true;
    });
  }

  private async readMechanicalWorks(
    gardenId: string,
    filters?: { dateFrom?: string; dateTo?: string }
  ): Promise<UnifiedOperation[]> {
    if (!this.storageProvider.getMechanicalWorks) return [];
    const logs = await this.storageProvider.getMechanicalWorks(gardenId);

    return (logs || []).map((log: any) =>
      this.asUnifiedOperation({
        id: `mechanical:${log.id}`,
        level: log.fieldRowId || log.row_id || log.bed_row_id ? 'row' : 'garden',
        type: 'work',
        gardenId,
        operationDate: log.work_date || log.date || log.created_at,
        quantity: log.duration_minutes || log.duration || undefined,
        unit: 'min',
        productName: log.machine_name || log.machineName,
        notes: log.notes,
        fieldRowId: log.fieldRowId || log.row_id || log.bed_row_id,
        sourceOperationId: log.id,
      })
    ).filter((item: UnifiedOperation) => {
      if (filters?.dateFrom && item.operationDate < filters.dateFrom) return false;
      if (filters?.dateTo && item.operationDate > filters.dateTo) return false;
      return true;
    });
  }

  private async readPlantOperations(
    gardenId: string,
    filters?: { plantId?: string; rowId?: string; dateFrom?: string; dateTo?: string }
  ): Promise<UnifiedOperation[]> {
    if (!this.storageProvider.getIndividualPlants || !this.storageProvider.getPlantOperations) return [];
    const plants = await this.storageProvider.getIndividualPlants(gardenId);

    const scopedPlants = (plants || []).filter((plant: any) => {
      if (filters?.plantId && plant.id !== filters.plantId) return false;
      if (filters?.rowId && plant.fieldRowId !== filters.rowId && plant.gardenRowId !== filters.rowId) return false;
      return true;
    });

    const operationLists = await Promise.all(
      scopedPlants.map((plant: any) => this.storageProvider.getPlantOperations?.(plant.id) ?? Promise.resolve([]))
    );

    const operations = operationLists.flat();
    return operations
      .map((operation: any) =>
        this.asUnifiedOperation({
          id: `plant:${operation.id}`,
          level: 'plant',
          type: operation.operationType || 'work',
          gardenId,
          operationDate: operation.operationDate || operation.date || operation.createdAt,
          operationTime: operation.operationTime,
          quantity: operation.quantity,
          unit: operation.unit,
          productName: operation.productName,
          notes: operation.notes,
          fieldRowId: operation.fieldRowId,
          gardenRowId: operation.gardenRowId,
          plantId: operation.plantId,
          sourceOperationId: operation.parentOperationId || operation.id,
          autoGenerated: operation.sourceType === 'orchestrator_auto' || operation.sourceType === 'orchestrator_sync',
          plantsAffected: 1,
        })
      )
      .filter((item) => {
        if (filters?.dateFrom && item.operationDate < filters.dateFrom) return false;
        if (filters?.dateTo && item.operationDate > filters.dateTo) return false;
        return true;
      });
  }

  private matchesUnifiedFilters(
    operation: UnifiedOperation,
    filters?: {
      level?: 'garden' | 'row' | 'plant';
      operationType?: string;
      rowId?: string;
      plantId?: string;
    }
  ) {
    if (!filters) return true;
    if (filters.level && operation.operationLevel !== filters.level) return false;
    if (filters.operationType && operation.operationType !== filters.operationType) return false;
    if (filters.rowId && operation.fieldRowId !== filters.rowId && operation.gardenRowId !== filters.rowId) return false;
    if (filters.plantId && operation.plantId !== filters.plantId) return false;
    return true;
  }

  private detectSyncSourceType(operation: UnifiedOperation): OperationSyncLog['sourceType'] {
    if (operation.operationType === 'watering') return 'watering';
    if (operation.operationType === 'fertilizing') return 'fertilizer';
    return 'treatment';
  }

  private async getBedIdForRow(rowId: string): Promise<string | undefined> {
    try {
      // This would query to find the bed that contains this row
      // For now, return undefined
      return undefined;
    } catch (error) {
      console.error('Error getting bed ID for row:', error);
      return undefined;
    }
  }

  private async getLatestSyncLog(
    sourceType: string,
    sourceOperationId: string
  ): Promise<OperationSyncLog | null> {
    try {
      // This would query the operation_sync_log table
      // For now, return null
      return null;
    } catch (error) {
      console.error('Error getting sync log:', error);
      return null;
    }
  }

  private async getPlantOperationsBySource(
    sourceType: string,
    sourceOperationId: string
  ): Promise<PlantOperation[]> {
    try {
      // This would query plant_operations with source filters
      // For now, return empty array
      return [];
    } catch (error) {
      console.error('Error getting plant operations by source:', error);
      return [];
    }
  }

  private parseWeatherTemperature(weather?: PlantOperation['weatherConditions']): number | undefined {
    const candidate = weather?.temp ?? (weather as any)?.temperature;
    const parsed = Number(candidate);
    return Number.isFinite(parsed) ? parsed : undefined;
  }
}

/**
 * UTILITY FUNCTIONS
 */

/**
 * Create unified operations service instance
 */
export const createUnifiedOperationsService = (storageProvider: IStorageProvider) => {
  return new UnifiedOperationsService(storageProvider);
};

/**
 * Execute bulk operation with unified approach
 */
export const executeBulkUnifiedOperation = async (
  storageProvider: IStorageProvider,
  request: UnifiedOperationRequest
): Promise<UnifiedOperationResponse> => {
  const service = createUnifiedOperationsService(storageProvider);
  return await service.executeUnifiedOperation(request);
};

/**
 * Get operation statistics for dashboard
 */
export interface OperationStatistics {
  totalOperations: number;
  operationsByType: Record<string, number>;
  operationsByLevel: Record<string, number>;
  plantsAffected: number;
  rowsAffected: number;
  autoGeneratedPercentage: number;
  recentSyncLogs: OperationSyncLog[];
}

export const getOperationStatistics = async (
  storageProvider: IStorageProvider,
  gardenId: string,
  dateFrom?: string,
  dateTo?: string
): Promise<OperationStatistics> => {
  try {
    const service = createUnifiedOperationsService(storageProvider);

    // Get operations and sync logs
    const [operations, syncLogs] = await Promise.all([
      service.getUnifiedOperations(gardenId, { dateFrom, dateTo }),
      service.getOperationSyncLogs(gardenId, { dateFrom, dateTo })
    ]);

    // Calculate statistics
    const operationsByType: Record<string, number> = {};
    const operationsByLevel: Record<string, number> = {};
    let autoGenerated = 0;
    const plantsAffected = new Set<string>();
    const rowsAffected = new Set<string>();

    operations.forEach(op => {
      // Count by type
      operationsByType[op.operationType] = (operationsByType[op.operationType] || 0) + 1;

      // Count by level
      operationsByLevel[op.granularityLevel] = (operationsByLevel[op.granularityLevel] || 0) + 1;

      // Count auto-generated
      if (op.autoGenerated) autoGenerated++;

      // Track affected entities
      if (op.plantId) plantsAffected.add(op.plantId);
      if (op.gardenRowId) rowsAffected.add(op.gardenRowId);
      if (op.fieldRowId) rowsAffected.add(op.fieldRowId);
    });

    return {
      totalOperations: operations.length,
      operationsByType,
      operationsByLevel,
      plantsAffected: plantsAffected.size,
      rowsAffected: rowsAffected.size,
      autoGeneratedPercentage: operations.length > 0 ? (autoGenerated / operations.length) * 100 : 0,
      recentSyncLogs: syncLogs.slice(0, 10)
    };
  } catch (error) {
    console.error('Error getting operation statistics:', error);
    return {
      totalOperations: 0,
      operationsByType: {},
      operationsByLevel: {},
      plantsAffected: 0,
      rowsAffected: 0,
      autoGeneratedPercentage: 0,
      recentSyncLogs: []
    };
  }
};

export default UnifiedOperationsService;
