-- ============================================
-- MIGRAZIONE: Aggiornamento plant_taxonomy e plant_synonyms
-- Generato automaticamente da generatePlantTaxonomyMigration.ts
-- Data: 2025-12-19T11:00:18.908Z
-- ============================================

-- Nuove famiglie botaniche
INSERT INTO plant_families (id, name, common_names) VALUES
  ('Lauraceae', 'Lauraceae', ARRAY['Lauracee']),
  ('Anacardiaceae', 'Anacardiaceae', ARRAY['Anacardiacee']),
  ('Moraceae', 'Moraceae', ARRAY['Moracee']),
  ('Vitaceae', 'Vitaceae', ARRAY['Vitacee']),
  ('Oleaceae', 'Oleaceae', ARRAY['Oleacee']),
  ('Caricaceae', 'Caricaceae', ARRAY['Caricacee']),
  ('Bromeliaceae', 'Bromeliaceae', ARRAY['Bromeliacee']),
  ('Musaceae', 'Musaceae', ARRAY['Musacee']),
  ('Rhamnaceae', 'Rhamnaceae', ARRAY['Rhamnacee']),
  ('Ericaceae', 'Ericaceae', ARRAY['Ericacee']),
  ('Myrtaceae', 'Myrtaceae', ARRAY['Mirtacee']),
  ('Adoxaceae', 'Adoxaceae', ARRAY['Adoxacee']),
  ('Cornaceae', 'Cornaceae', ARRAY['Cornacee']),
  ('Grossulariaceae', 'Grossulariaceae', ARRAY['Grossulariacee'])
ON CONFLICT (id) DO NOTHING;


-- Aggiornamento plant_taxonomy
INSERT INTO plant_taxonomy (plant_id, names, family_id, archetype_id, functional_category, tags) VALUES
  ('pomodoro', '{"it":"Pomodoro","en":"Solanum"}'::jsonb, 'Solanaceae', 'A1', 'FRUIT', ARRAY['orto', 'estivo']),
  ('peperoncino', '{"it":"Peperoncino","en":"Capsicum"}'::jsonb, 'Solanaceae', 'A1', 'FRUIT', ARRAY['orto', 'estivo']),
  ('zucchina', '{"it":"Zucchina","en":"Cucurbita"}'::jsonb, 'Cucurbitaceae', 'A2', 'FRUIT', ARRAY['orto', 'estivo']),
  ('melanzana', '{"it":"Melanzana","en":"Solanum"}'::jsonb, 'Solanaceae', 'A1', 'FRUIT', ARRAY['orto', 'estivo']),
  ('lattuga', '{"it":"Lattuga","en":"Lactuca"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('basilico', '{"it":"Basilico","en":"Ocimum"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('fagiolo', '{"it":"Fagiolo","en":"Phaseolus"}'::jsonb, 'Fabaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('pisello', '{"it":"Pisello","en":"Pisum"}'::jsonb, 'Fabaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('carota', '{"it":"Carota","en":"Daucus"}'::jsonb, 'Apiaceae', 'A6', 'ROOT', ARRAY['orto', 'primaverile']),
  ('cipolla', '{"it":"Cipolla","en":"Allium"}'::jsonb, 'Amaryllidaceae', 'A5', 'ROOT', ARRAY['orto', 'primaverile']),
  ('patata', '{"it":"Patata","en":"Solanum"}'::jsonb, 'Solanaceae', 'A1', 'ROOT', ARRAY['orto', 'primaverile']),
  ('radicchio', '{"it":"Radicchio","en":"Cichorium"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('spinacio', '{"it":"Spinacio","en":"Spinacia"}'::jsonb, 'Amaranthaceae', 'A8', 'LEAF', ARRAY['orto', 'invernale']),
  ('finocchio', '{"it":"Finocchio","en":"Foeniculum"}'::jsonb, 'Apiaceae', 'A6', 'ROOT', ARRAY['orto', 'primaverile']),
  ('mais', '{"it":"Mais","en":"Zea"}'::jsonb, 'Poaceae', 'A4', 'FRUIT', ARRAY['orto', 'estivo']),
  ('frumento', '{"it":"Frumento","en":"Triticum"}'::jsonb, 'Poaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('basilico', '{"it":"Basilico","en":"Ocimum"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('rosmarino', '{"it":"Rosmarino","en":"Rosmarinus"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('salvia', '{"it":"Salvia","en":"Salvia"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('timo', '{"it":"Timo","en":"Thymus"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('origano', '{"it":"Origano","en":"Origanum"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('menta', '{"it":"Menta","en":"Mentha"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('lavanda', '{"it":"Lavanda","en":"Lavandula"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('zucca', '{"it":"Zucca","en":"Cucurbita"}'::jsonb, 'Cucurbitaceae', 'A2', 'FRUIT', ARRAY['orto', 'estivo']),
  ('cetriolo', '{"it":"Cetriolo","en":"Cucumis"}'::jsonb, 'Cucurbitaceae', 'A2', 'FRUIT', ARRAY['orto', 'estivo']),
  ('melone', '{"it":"Melone","en":"Cucumis"}'::jsonb, 'Cucurbitaceae', 'A2', 'FRUIT', ARRAY['orto', 'estivo']),
  ('anguria', '{"it":"Anguria","en":"Citrullus"}'::jsonb, 'Cucurbitaceae', 'A2', 'FRUIT', ARRAY['orto', 'estivo']),
  ('peperone-dolce', '{"it":"Peperone dolce","en":"Capsicum"}'::jsonb, 'Solanaceae', 'A1', 'FRUIT', ARRAY['orto', 'estivo']),
  ('aglio', '{"it":"Aglio","en":"Allium"}'::jsonb, 'Amaryllidaceae', 'A5', 'ROOT', ARRAY['orto', 'primaverile']),
  ('porro', '{"it":"Porro","en":"Allium"}'::jsonb, 'Amaryllidaceae', 'A5', 'ROOT', ARRAY['orto', 'primaverile']),
  ('scalogno', '{"it":"Scalogno","en":"Allium"}'::jsonb, 'Amaryllidaceae', 'A5', 'ROOT', ARRAY['orto', 'primaverile']),
  ('barbabietola-rossa', '{"it":"Barbabietola rossa","en":"Beta"}'::jsonb, 'Amaranthaceae', 'A8', 'ROOT', ARRAY['orto', 'primaverile']),
  ('rapa', '{"it":"Rapa","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'ROOT', ARRAY['orto', 'primaverile']),
  ('ravanello', '{"it":"Ravanello","en":"Raphanus"}'::jsonb, 'Brassicaceae', 'A3', 'ROOT', ARRAY['orto', 'primaverile']),
  ('sedano', '{"it":"Sedano","en":"Apium"}'::jsonb, 'Apiaceae', 'A6', 'ROOT', ARRAY['orto', 'primaverile']),
  ('sedano-rapa', '{"it":"Sedano rapa","en":"Apium"}'::jsonb, 'Apiaceae', 'A6', 'ROOT', ARRAY['orto', 'primaverile']),
  ('prezzemolo', '{"it":"Prezzemolo","en":"Petroselinum"}'::jsonb, 'Apiaceae', 'A6', 'LEAF', ARRAY['orto', 'invernale']),
  ('carciofo', '{"it":"Carciofo","en":"Cynara"}'::jsonb, 'Asteraceae', 'A7', 'FRUIT', ARRAY['orto', 'estivo']),
  ('asparago', '{"it":"Asparago","en":"Asparagus"}'::jsonb, 'Amaryllidaceae', 'A5', 'ROOT', ARRAY['orto', 'primaverile']),
  ('rucola', '{"it":"Rucola","en":"Eruca"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('pastinaca', '{"it":"Pastinaca","en":"Pastinaca"}'::jsonb, 'Apiaceae', 'A6', 'ROOT', ARRAY['orto', 'primaverile']),
  ('topinambur', '{"it":"Topinambur","en":"Helianthus"}'::jsonb, 'Asteraceae', 'A7', 'ROOT', ARRAY['orto', 'primaverile']),
  ('patata-dolce', '{"it":"Patata dolce","en":"Ipomoea"}'::jsonb, 'Solanaceae', 'A1', 'ROOT', ARRAY['orto', 'primaverile']),
  ('erba-cipollina', '{"it":"Erba cipollina","en":"Allium"}'::jsonb, 'Amaryllidaceae', 'A5', 'LEAF', ARRAY['orto', 'invernale']),
  ('lattuga-romana', '{"it":"Lattuga romana","en":"Lactuca"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('lattuga-iceberg', '{"it":"Lattuga iceberg","en":"Lactuca"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('indivia-riccia', '{"it":"Indivia riccia","en":"Cichorium"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('scarola', '{"it":"Scarola","en":"Cichorium"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('cicoria', '{"it":"Cicoria","en":"Cichorium"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('catalogna', '{"it":"Catalogna","en":"Cichorium"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('puntarelle', '{"it":"Puntarelle","en":"Cichorium"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('radicchio-variegato-castelfranco', '{"it":"Radicchio variegato castelfranco","en":"Cichorium"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('valeriana-songino', '{"it":"Valeriana (songino)","en":"Valerianella"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('bietola-da-costa', '{"it":"Bietola da costa","en":"Beta"}'::jsonb, 'Amaranthaceae', 'A8', 'LEAF', ARRAY['orto', 'invernale']),
  ('bietola-da-taglio', '{"it":"Bietola da taglio","en":"Beta"}'::jsonb, 'Amaranthaceae', 'A8', 'LEAF', ARRAY['orto', 'invernale']),
  ('spinacio-neozelandese', '{"it":"Spinacio neozelandese","en":"Tetragonia"}'::jsonb, 'Amaranthaceae', 'A8', 'LEAF', ARRAY['orto', 'invernale']),
  ('crescione', '{"it":"Crescione","en":"Lepidium"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('portulaca', '{"it":"Portulaca","en":"Portulaca"}'::jsonb, 'Amaranthaceae', 'A8', 'LEAF', ARRAY['orto', 'invernale']),
  ('cavolfiore', '{"it":"Cavolfiore","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('broccolo', '{"it":"Broccolo","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('cavolo-romanesco', '{"it":"Cavolo romanesco","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('cavolo-cappuccio', '{"it":"Cavolo cappuccio","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('cavolo-verza', '{"it":"Cavolo verza","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('cavolo-nero', '{"it":"Cavolo nero","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('cavolo-riccio-kale', '{"it":"Cavolo riccio (kale)","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('cavolo-rosso', '{"it":"Cavolo rosso","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('cavolini-di-bruxelles', '{"it":"Cavolini di bruxelles","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('cime-di-rapa', '{"it":"Cime di rapa","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('cavolo-rapa-kohlrabi', '{"it":"Cavolo rapa (kohlrabi)","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'ROOT', ARRAY['orto', 'primaverile']),
  ('cavolo-cinese-pak-choi', '{"it":"Cavolo cinese (pak choi)","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('broccolo-spigariello', '{"it":"Broccolo spigariello","en":"Brassica"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('fagiolino', '{"it":"Fagiolino","en":"Phaseolus"}'::jsonb, 'Fabaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('fagiolo-secco', '{"it":"Fagiolo secco","en":"Phaseolus"}'::jsonb, 'Fabaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('pisello-mangiatutto', '{"it":"Pisello mangiatutto","en":"Pisum"}'::jsonb, 'Fabaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('fava', '{"it":"Fava","en":"Vicia"}'::jsonb, 'Fabaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('ceci', '{"it":"Ceci","en":"Cicer"}'::jsonb, 'Fabaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('lenticchia', '{"it":"Lenticchia","en":"Lens"}'::jsonb, 'Fabaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('lupino', '{"it":"Lupino","en":"Lupinus"}'::jsonb, 'Fabaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('cicerchia', '{"it":"Cicerchia","en":"Lathyrus"}'::jsonb, 'Fabaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('soia', '{"it":"Soia","en":"Glycine"}'::jsonb, 'Fabaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('taccole', '{"it":"Taccole","en":"Pisum"}'::jsonb, 'Fabaceae', 'A4', 'LEGUME', ARRAY['orto']),
  ('maggiorana', '{"it":"Maggiorana","en":"Origanum"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('alloro', '{"it":"Alloro","en":"Laurus"}'::jsonb, 'Lauraceae', 'A10', 'LEAF', ARRAY['orto', 'invernale']),
  ('coriandolo', '{"it":"Coriandolo","en":"Coriandrum"}'::jsonb, 'Apiaceae', 'A6', 'LEAF', ARRAY['orto', 'invernale']),
  ('aneto', '{"it":"Aneto","en":"Anethum"}'::jsonb, 'Apiaceae', 'A6', 'LEAF', ARRAY['orto', 'invernale']),
  ('finocchietto-selvatico', '{"it":"Finocchietto selvatico","en":"Foeniculum"}'::jsonb, 'Apiaceae', 'A6', 'LEAF', ARRAY['orto', 'invernale']),
  ('santoreggia', '{"it":"Santoreggia","en":"Satureja"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('melissa', '{"it":"Melissa","en":"Melissa"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('erba-luigia-cedrina', '{"it":"Erba luigia (cedrina)","en":"Aloysia"}'::jsonb, 'Verbenaceae', 'A1', 'LEAF', ARRAY['orto', 'invernale']),
  ('dragoncello', '{"it":"Dragoncello","en":"Artemisia"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('ruta', '{"it":"Ruta","en":"Ruta"}'::jsonb, 'Rutaceae', 'A12', 'LEAF', ARRAY['orto', 'invernale']),
  ('borragine', '{"it":"Borragine","en":"Borago"}'::jsonb, 'Boraginaceae', 'A1', 'LEAF', ARRAY['orto', 'invernale']),
  ('calendula-edibile', '{"it":"Calendula edibile","en":"Calendula"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('nasturzio-edibile', '{"it":"Nasturzio edibile","en":"Tropaeolum"}'::jsonb, 'Tropaeolaceae', 'A1', 'LEAF', ARRAY['orto', 'invernale']),
  ('camomilla', '{"it":"Camomilla","en":"Matricaria"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('zafferano', '{"it":"Zafferano","en":"Crocus"}'::jsonb, 'Iridaceae', 'A1', 'ROOT', ARRAY['orto', 'primaverile']),
  ('cappero', '{"it":"Cappero","en":"Capparis"}'::jsonb, 'Capparaceae', 'A1', 'LEAF', ARRAY['orto', 'invernale']),
  ('cardo', '{"it":"Cardo","en":"Cynara"}'::jsonb, 'Asteraceae', 'A7', 'LEAF', ARRAY['orto', 'invernale']),
  ('scorzonera', '{"it":"Scorzonera","en":"Scorzonera"}'::jsonb, 'Asteraceae', 'A7', 'ROOT', ARRAY['orto', 'primaverile']),
  ('salsefrica', '{"it":"Salsefrica","en":"Tragopogon"}'::jsonb, 'Asteraceae', 'A7', 'ROOT', ARRAY['orto', 'primaverile']),
  ('rafano', '{"it":"Rafano","en":"Armoracia"}'::jsonb, 'Brassicaceae', 'A3', 'ROOT', ARRAY['orto', 'primaverile']),
  ('senape-semi', '{"it":"Senape (semi)","en":"Sinapis"}'::jsonb, 'Brassicaceae', 'A3', 'LEAF', ARRAY['orto', 'invernale']),
  ('fragola-bosco', '{"it":"Fragola di bosco","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-elsanta', '{"it":"Fragola elsanta","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-albion', '{"it":"Fragola albion","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-seascape', '{"it":"Fragola seascape","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-candonga', '{"it":"Fragola candonga","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-matera', '{"it":"Fragola matera","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-sabrina', '{"it":"Fragola sabrina","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-alba', '{"it":"Fragola alba","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-clery', '{"it":"Fragola clery","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-eliany', '{"it":"Fragola eliany","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-florence', '{"it":"Fragola florence","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-gariguette', '{"it":"Fragola gariguette","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-malga', '{"it":"Fragola malga","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-roxana', '{"it":"Fragola roxana","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragola-siria', '{"it":"Fragola siria","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fragolina-di-bosco', '{"it":"Fragolina di bosco","en":"Fragaria"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('melo-golden', '{"it":"Melo golden delicious","en":"Malus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('melo-fuji', '{"it":"Melo fuji","en":"Malus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('pero-abate', '{"it":"Pero abate fetel","en":"Pyrus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('pesco-gialla', '{"it":"Pesco pesca gialla","en":"Prunus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('ciliegio-durone', '{"it":"Ciliegio durone","en":"Prunus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('cotogno', '{"it":"Cotogno","en":"Cydonia"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('nespolo-del-giappone', '{"it":"Nespolo del giappone","en":"Eriobotrya"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('nespolo-comune', '{"it":"Nespolo comune","en":"Mespilus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('nettarino', '{"it":"Nettarino","en":"Prunus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('albicocco', '{"it":"Albicocco","en":"Prunus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('susino', '{"it":"Susino","en":"Prunus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('ciliegio-acido-amarena', '{"it":"Ciliegio acido (amarena)","en":"Prunus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('mandorlo', '{"it":"Mandorlo","en":"Prunus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('nocciolo', '{"it":"Nocciolo","en":"Corylus"}'::jsonb, 'Betulaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('noce', '{"it":"Noce","en":"Juglans"}'::jsonb, 'Juglandaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('castagno', '{"it":"Castagno","en":"Castanea"}'::jsonb, 'Fagaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('pistacchio', '{"it":"Pistacchio","en":"Pistacia"}'::jsonb, 'Anacardiaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fico', '{"it":"Fico","en":"Ficus"}'::jsonb, 'Moraceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('fico-dindia', '{"it":"Fico d''india","en":"Opuntia"}'::jsonb, 'Cactaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('melograno', '{"it":"Melograno","en":"Punica"}'::jsonb, 'Lythraceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('cachi', '{"it":"Cachi","en":"Diospyros"}'::jsonb, 'Ebenaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('kiwi', '{"it":"Kiwi","en":"Actinidia"}'::jsonb, 'Actinidiaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('uva-da-tavola', '{"it":"Uva da tavola","en":"Vitis"}'::jsonb, 'Vitaceae', 'A11', 'SPECIALIZED', ARRAY['frutteto']),
  ('limone', '{"it":"Limone","en":"Citrus"}'::jsonb, 'Rutaceae', 'A12', 'SPECIALIZED', ARRAY['frutteto']),
  ('arancio-dolce', '{"it":"Arancio dolce","en":"Citrus"}'::jsonb, 'Rutaceae', 'A12', 'SPECIALIZED', ARRAY['frutteto']),
  ('arancio-amaro', '{"it":"Arancio amaro","en":"Citrus"}'::jsonb, 'Rutaceae', 'A12', 'SPECIALIZED', ARRAY['frutteto']),
  ('mandarino', '{"it":"Mandarino","en":"Citrus"}'::jsonb, 'Rutaceae', 'A12', 'SPECIALIZED', ARRAY['frutteto']),
  ('clementino', '{"it":"Clementino","en":"Citrus"}'::jsonb, 'Rutaceae', 'A12', 'SPECIALIZED', ARRAY['frutteto']),
  ('bergamotto', '{"it":"Bergamotto","en":"Citrus"}'::jsonb, 'Rutaceae', 'A12', 'SPECIALIZED', ARRAY['frutteto']),
  ('pompelmo', '{"it":"Pompelmo","en":"Citrus"}'::jsonb, 'Rutaceae', 'A12', 'SPECIALIZED', ARRAY['frutteto']),
  ('cedro', '{"it":"Cedro","en":"Citrus"}'::jsonb, 'Rutaceae', 'A12', 'SPECIALIZED', ARRAY['frutteto']),
  ('lime', '{"it":"Lime","en":"Citrus"}'::jsonb, 'Rutaceae', 'A12', 'SPECIALIZED', ARRAY['frutteto']),
  ('kumquat', '{"it":"Kumquat","en":"Fortunella"}'::jsonb, 'Rutaceae', 'A12', 'SPECIALIZED', ARRAY['frutteto']),
  ('chinotto', '{"it":"Chinotto","en":"Citrus"}'::jsonb, 'Rutaceae', 'A12', 'SPECIALIZED', ARRAY['frutteto']),
  ('melo-gala', '{"it":"Melo gala","en":"Malus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('melo-granny-smith', '{"it":"Melo granny smith","en":"Malus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('melo-red-delicious', '{"it":"Melo red delicious","en":"Malus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('melo-renetta', '{"it":"Melo renetta","en":"Malus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('pero-abate-fetel', '{"it":"Pero abate fetel","en":"Pyrus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('pero-williams', '{"it":"Pero williams","en":"Pyrus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('pero-conference', '{"it":"Pero conference","en":"Pyrus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('pero-kaiser', '{"it":"Pero kaiser","en":"Pyrus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('pero-decana-del-comizio', '{"it":"Pero decana del comizio","en":"Pyrus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('pero-coscia', '{"it":"Pero coscia","en":"Pyrus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('olivo-frantoio', '{"it":"Olivo frantoio","en":"Olea"}'::jsonb, 'Oleaceae', 'A11', 'SPECIALIZED', ARRAY['frutteto']),
  ('olivo-leccino', '{"it":"Olivo leccino","en":"Olea"}'::jsonb, 'Oleaceae', 'A11', 'SPECIALIZED', ARRAY['frutteto']),
  ('olivo-moraiolo', '{"it":"Olivo moraiolo","en":"Olea"}'::jsonb, 'Oleaceae', 'A11', 'SPECIALIZED', ARRAY['frutteto']),
  ('olivo-pendolino', '{"it":"Olivo pendolino","en":"Olea"}'::jsonb, 'Oleaceae', 'A11', 'SPECIALIZED', ARRAY['frutteto']),
  ('vite-sangiovese', '{"it":"Vite sangiovese","en":"Vitis"}'::jsonb, 'Vitaceae', 'A11', 'SPECIALIZED', ARRAY['frutteto']),
  ('vite-nebbiolo', '{"it":"Vite nebbiolo","en":"Vitis"}'::jsonb, 'Vitaceae', 'A11', 'SPECIALIZED', ARRAY['frutteto']),
  ('vite-barbera', '{"it":"Vite barbera","en":"Vitis"}'::jsonb, 'Vitaceae', 'A11', 'SPECIALIZED', ARRAY['frutteto']),
  ('vite-montepulciano', '{"it":"Vite montepulciano","en":"Vitis"}'::jsonb, 'Vitaceae', 'A11', 'SPECIALIZED', ARRAY['frutteto']),
  ('vite-trebbiano', '{"it":"Vite trebbiano","en":"Vitis"}'::jsonb, 'Vitaceae', 'A11', 'SPECIALIZED', ARRAY['frutteto']),
  ('vite-chardonnay', '{"it":"Vite chardonnay","en":"Vitis"}'::jsonb, 'Vitaceae', 'A11', 'SPECIALIZED', ARRAY['frutteto']),
  ('vite-pinot-grigio', '{"it":"Vite pinot grigio","en":"Vitis"}'::jsonb, 'Vitaceae', 'A11', 'SPECIALIZED', ARRAY['frutteto']),
  ('papaya-comune', '{"it":"Papaya","en":"Carica"}'::jsonb, 'Caricaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('mango-kent', '{"it":"Mango kent","en":"Mangifera"}'::jsonb, 'Anacardiaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('avocado-hass', '{"it":"Avocado hass","en":"Persea"}'::jsonb, 'Lauraceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('ananas-comune', '{"it":"Ananas","en":"Ananas"}'::jsonb, 'Bromeliaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('banano-nano', '{"it":"Banano nano","en":"Musa"}'::jsonb, 'Musaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('gelso', '{"it":"Gelso","en":"Morus"}'::jsonb, 'Moraceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('giuggiolo', '{"it":"Giuggiolo","en":"Ziziphus"}'::jsonb, 'Rhamnaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('corbezzolo', '{"it":"Corbezzolo","en":"Arbutus"}'::jsonb, 'Ericaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('mirto', '{"it":"Mirto","en":"Myrtus"}'::jsonb, 'Myrtaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('sorbo-domestico', '{"it":"Sorbo domestico","en":"Sorbus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('azzarolo', '{"it":"Azzarolo","en":"Crataegus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('carrubo', '{"it":"Carrubo","en":"Ceratonia"}'::jsonb, 'Fabaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('alchechengi', '{"it":"Alchechengi","en":"Physalis"}'::jsonb, 'Solanaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('sambuco', '{"it":"Sambuco","en":"Sambucus"}'::jsonb, 'Adoxaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('corniolo', '{"it":"Corniolo","en":"Cornus"}'::jsonb, 'Cornaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('prugnolo', '{"it":"Prugnolo","en":"Prunus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('lampone-tulameen', '{"it":"Lampone tulameen","en":"Rubus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('lampone-glen-ample', '{"it":"Lampone glen ample","en":"Rubus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('lampone-heritage', '{"it":"Lampone heritage","en":"Rubus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('lampone-autumn-bliss', '{"it":"Lampone autumn bliss","en":"Rubus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('mora', '{"it":"Mora","en":"Rubus"}'::jsonb, 'Rosaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('mirtillo', '{"it":"Mirtillo","en":"Vaccinium"}'::jsonb, 'Ericaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('ribes-rosso', '{"it":"Ribes rosso","en":"Ribes"}'::jsonb, 'Grossulariaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('ribes-nero', '{"it":"Ribes nero","en":"Ribes"}'::jsonb, 'Grossulariaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('uva-spina', '{"it":"Uva spina","en":"Ribes"}'::jsonb, 'Grossulariaceae', 'A10', 'SPECIALIZED', ARRAY['frutteto']),
  ('basilico', '{"it":"Basilico","en":"Ocimum"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('rosmarino', '{"it":"Rosmarino","en":"Rosmarinus"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('salvia', '{"it":"Salvia","en":"Salvia"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('timo', '{"it":"Timo","en":"Thymus"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('origano', '{"it":"Origano","en":"Origanum"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('menta', '{"it":"Menta","en":"Mentha"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto']),
  ('lavanda', '{"it":"Lavanda","en":"Lavandula"}'::jsonb, 'Lamiaceae', 'A9', 'AROMATIC', ARRAY['orto'])
ON CONFLICT (plant_id) DO UPDATE SET
  names = EXCLUDED.names,
  family_id = EXCLUDED.family_id,
  archetype_id = EXCLUDED.archetype_id,
  functional_category = EXCLUDED.functional_category,
  tags = EXCLUDED.tags,
  updated_at = NOW();


-- Inserimento sinonimi
INSERT INTO plant_synonyms (synonym, normalized_synonym, plant_id, locale, confidence, source) VALUES
  ('banana', 'banana', 'banano', 'it', 1.0, 'system'),
  ('banane', 'banane', 'banano', 'it', 1.0, 'system'),
  ('grano', 'grano', 'frumento', 'it', 1.0, 'system'),
  ('grano tenero', 'grano tenero', 'frumento', 'it', 1.0, 'system'),
  ('grano duro', 'grano duro', 'frumento', 'it', 1.0, 'system'),
  ('triticum', 'triticum', 'frumento', 'it', 1.0, 'system'),
  ('triticum aestivum', 'triticum aestivum', 'frumento', 'it', 1.0, 'system'),
  ('triticum durum', 'triticum durum', 'frumento', 'it', 1.0, 'system'),
  ('mais', 'mais', 'mais', 'it', 1.0, 'system'),
  ('granturco', 'granturco', 'mais', 'it', 1.0, 'system'),
  ('granoturco', 'granoturco', 'mais', 'it', 1.0, 'system'),
  ('orzo', 'orzo', 'orzo', 'it', 1.0, 'system'),
  ('avena', 'avena', 'avena', 'it', 1.0, 'system'),
  ('patate', 'patate', 'patata', 'it', 1.0, 'system'),
  ('patata', 'patata', 'patata', 'it', 1.0, 'system'),
  ('radicchi', 'radicchi', 'radicchio', 'it', 1.0, 'system'),
  ('radicchio', 'radicchio', 'radicchio', 'it', 1.0, 'system'),
  ('spinaci', 'spinaci', 'spinacio', 'it', 1.0, 'system'),
  ('spinacio', 'spinacio', 'spinacio', 'it', 1.0, 'system'),
  ('finocchi', 'finocchi', 'finocchio', 'it', 1.0, 'system'),
  ('finocchio', 'finocchio', 'finocchio', 'it', 1.0, 'system'),
  ('pomodori', 'pomodori', 'pomodoro', 'it', 1.0, 'system'),
  ('pomodoro', 'pomodoro', 'pomodoro', 'it', 1.0, 'system'),
  ('peperoncini', 'peperoncini', 'peperoncino', 'it', 1.0, 'system'),
  ('peperoncino', 'peperoncino', 'peperoncino', 'it', 1.0, 'system'),
  ('zucchine', 'zucchine', 'zucchina', 'it', 1.0, 'system'),
  ('zucchina', 'zucchina', 'zucchina', 'it', 1.0, 'system'),
  ('zucchino', 'zucchino', 'zucchina', 'it', 1.0, 'system'),
  ('melanzane', 'melanzane', 'melanzana', 'it', 1.0, 'system'),
  ('melanzana', 'melanzana', 'melanzana', 'it', 1.0, 'system'),
  ('lattughe', 'lattughe', 'lattuga', 'it', 1.0, 'system'),
  ('lattuga', 'lattuga', 'lattuga', 'it', 1.0, 'system'),
  ('fagioli', 'fagioli', 'fagiolo', 'it', 1.0, 'system'),
  ('fagiolo', 'fagiolo', 'fagiolo', 'it', 1.0, 'system'),
  ('piselli', 'piselli', 'pisello', 'it', 1.0, 'system'),
  ('pisello', 'pisello', 'pisello', 'it', 1.0, 'system'),
  ('carote', 'carote', 'carota', 'it', 1.0, 'system'),
  ('carota', 'carota', 'carota', 'it', 1.0, 'system'),
  ('cipolle', 'cipolle', 'cipolla', 'it', 1.0, 'system'),
  ('cipolla', 'cipolla', 'cipolla', 'it', 1.0, 'system'),
  ('basilici', 'basilici', 'basilico', 'it', 1.0, 'system'),
  ('basilico', 'basilico', 'basilico', 'it', 1.0, 'system'),
  ('rosmarini', 'rosmarini', 'rosmarino', 'it', 1.0, 'system'),
  ('rosmarino', 'rosmarino', 'rosmarino', 'it', 1.0, 'system'),
  ('salvie', 'salvie', 'salvia', 'it', 1.0, 'system'),
  ('salvia', 'salvia', 'salvia', 'it', 1.0, 'system'),
  ('fragole', 'fragole', 'fragola', 'it', 1.0, 'system'),
  ('fragola', 'fragola', 'fragola', 'it', 1.0, 'system'),
  ('lamponi', 'lamponi', 'lampone', 'it', 1.0, 'system'),
  ('lampone', 'lampone', 'lampone', 'it', 1.0, 'system'),
  ('mirtilli', 'mirtilli', 'mirtillo', 'it', 1.0, 'system'),
  ('mirtillo', 'mirtillo', 'mirtillo', 'it', 1.0, 'system'),
  ('melo', 'melo', 'melo', 'it', 1.0, 'system'),
  ('meli', 'meli', 'melo', 'it', 1.0, 'system'),
  ('mela', 'mela', 'melo', 'it', 1.0, 'system'),
  ('mele', 'mele', 'melo', 'it', 1.0, 'system'),
  ('pero', 'pero', 'pero', 'it', 1.0, 'system'),
  ('peri', 'peri', 'pero', 'it', 1.0, 'system'),
  ('pera', 'pera', 'pero', 'it', 1.0, 'system'),
  ('pere', 'pere', 'pero', 'it', 1.0, 'system'),
  ('pesco', 'pesco', 'pesco', 'it', 1.0, 'system'),
  ('peschi', 'peschi', 'pesco', 'it', 1.0, 'system'),
  ('pesca', 'pesca', 'pesco', 'it', 1.0, 'system'),
  ('pesche', 'pesche', 'pesco', 'it', 1.0, 'system'),
  ('albicocco', 'albicocco', 'albicocco', 'it', 1.0, 'system'),
  ('albicocchi', 'albicocchi', 'albicocco', 'it', 1.0, 'system'),
  ('albicocca', 'albicocca', 'albicocco', 'it', 1.0, 'system'),
  ('albicocche', 'albicocche', 'albicocco', 'it', 1.0, 'system'),
  ('ciliegio', 'ciliegio', 'ciliegio', 'it', 1.0, 'system'),
  ('ciliegi', 'ciliegi', 'ciliegio', 'it', 1.0, 'system'),
  ('ciliegia', 'ciliegia', 'ciliegio', 'it', 1.0, 'system'),
  ('ciliegie', 'ciliegie', 'ciliegio', 'it', 1.0, 'system'),
  ('olivo', 'olivo', 'olivo', 'it', 1.0, 'system'),
  ('olivi', 'olivi', 'olivo', 'it', 1.0, 'system'),
  ('oliva', 'oliva', 'olivo', 'it', 1.0, 'system'),
  ('olive', 'olive', 'olivo', 'it', 1.0, 'system'),
  ('vite', 'vite', 'vite', 'it', 1.0, 'system'),
  ('viti', 'viti', 'vite', 'it', 1.0, 'system'),
  ('uva', 'uva', 'vite', 'it', 1.0, 'system'),
  ('zucche', 'zucche', 'zucca', 'it', 1.0, 'system'),
  ('zucca', 'zucca', 'zucca', 'it', 1.0, 'system'),
  ('cetrioli', 'cetrioli', 'cetriolo', 'it', 1.0, 'system'),
  ('cetriolo', 'cetriolo', 'cetriolo', 'it', 1.0, 'system'),
  ('meloni', 'meloni', 'melone', 'it', 1.0, 'system'),
  ('melone', 'melone', 'melone', 'it', 1.0, 'system'),
  ('angurie', 'angurie', 'anguria', 'it', 1.0, 'system'),
  ('anguria', 'anguria', 'anguria', 'it', 1.0, 'system'),
  ('cocomero', 'cocomero', 'anguria', 'it', 1.0, 'system'),
  ('peperoni', 'peperoni', 'peperone-dolce', 'it', 1.0, 'system'),
  ('peperone', 'peperone', 'peperone-dolce', 'it', 1.0, 'system'),
  ('agli', 'agli', 'aglio', 'it', 1.0, 'system'),
  ('aglio', 'aglio', 'aglio', 'it', 1.0, 'system'),
  ('porri', 'porri', 'porro', 'it', 1.0, 'system'),
  ('porro', 'porro', 'porro', 'it', 1.0, 'system'),
  ('scalogni', 'scalogni', 'scalogno', 'it', 1.0, 'system'),
  ('scalogno', 'scalogno', 'scalogno', 'it', 1.0, 'system'),
  ('barbabietole', 'barbabietole', 'barbabietola-rossa', 'it', 1.0, 'system'),
  ('barbabietola', 'barbabietola', 'barbabietola-rossa', 'it', 1.0, 'system'),
  ('rape', 'rape', 'rapa', 'it', 1.0, 'system'),
  ('rapa', 'rapa', 'rapa', 'it', 1.0, 'system'),
  ('ravanelli', 'ravanelli', 'ravanello', 'it', 1.0, 'system'),
  ('ravanello', 'ravanello', 'ravanello', 'it', 1.0, 'system'),
  ('sedani', 'sedani', 'sedano', 'it', 1.0, 'system'),
  ('sedano', 'sedano', 'sedano', 'it', 1.0, 'system'),
  ('prezzemoli', 'prezzemoli', 'prezzemolo', 'it', 1.0, 'system'),
  ('prezzemolo', 'prezzemolo', 'prezzemolo', 'it', 1.0, 'system'),
  ('carciofi', 'carciofi', 'carciofo', 'it', 1.0, 'system'),
  ('carciofo', 'carciofo', 'carciofo', 'it', 1.0, 'system'),
  ('asparagi', 'asparagi', 'asparago', 'it', 1.0, 'system'),
  ('asparago', 'asparago', 'asparago', 'it', 1.0, 'system'),
  ('rucole', 'rucole', 'rucola', 'it', 1.0, 'system'),
  ('rucola', 'rucola', 'rucola', 'it', 1.0, 'system'),
  ('pastinache', 'pastinache', 'pastinaca', 'it', 1.0, 'system'),
  ('pastinaca', 'pastinaca', 'pastinaca', 'it', 1.0, 'system'),
  ('topinambur', 'topinambur', 'topinambur', 'it', 1.0, 'system'),
  ('topinamburi', 'topinamburi', 'topinambur', 'it', 1.0, 'system'),
  ('patate-dolci', 'patate-dolci', 'patata-dolce', 'it', 1.0, 'system'),
  ('patata-dolce', 'patata-dolce', 'patata-dolce', 'it', 1.0, 'system'),
  ('batata', 'batata', 'patata-dolce', 'it', 1.0, 'system'),
  ('erba-cipollina', 'erba-cipollina', 'erba-cipollina', 'it', 1.0, 'system'),
  ('erba cipollina', 'erba cipollina', 'erba-cipollina', 'it', 1.0, 'system'),
  ('indivie', 'indivie', 'indivia-riccia', 'it', 1.0, 'system'),
  ('indivia', 'indivia', 'indivia-riccia', 'it', 1.0, 'system'),
  ('scarole', 'scarole', 'scarola', 'it', 1.0, 'system'),
  ('scarola', 'scarola', 'scarola', 'it', 1.0, 'system'),
  ('cicorie', 'cicorie', 'cicoria', 'it', 1.0, 'system'),
  ('cicoria', 'cicoria', 'cicoria', 'it', 1.0, 'system'),
  ('catalogne', 'catalogne', 'catalogna', 'it', 1.0, 'system'),
  ('catalogna', 'catalogna', 'catalogna', 'it', 1.0, 'system'),
  ('puntarelle', 'puntarelle', 'puntarelle', 'it', 1.0, 'system'),
  ('puntarella', 'puntarella', 'puntarelle', 'it', 1.0, 'system'),
  ('bietole', 'bietole', 'bietola-da-costa', 'it', 1.0, 'system'),
  ('bietola', 'bietola', 'bietola-da-costa', 'it', 1.0, 'system'),
  ('crescioni', 'crescioni', 'crescione', 'it', 1.0, 'system'),
  ('crescione', 'crescione', 'crescione', 'it', 1.0, 'system'),
  ('portulache', 'portulache', 'portulaca', 'it', 1.0, 'system'),
  ('portulaca', 'portulaca', 'portulaca', 'it', 1.0, 'system'),
  ('cavolfiori', 'cavolfiori', 'cavolfiore', 'it', 1.0, 'system'),
  ('cavolfiore', 'cavolfiore', 'cavolfiore', 'it', 1.0, 'system'),
  ('broccoli', 'broccoli', 'broccolo', 'it', 1.0, 'system'),
  ('broccolo', 'broccolo', 'broccolo', 'it', 1.0, 'system'),
  ('cavolo-romanesco', 'cavolo-romanesco', 'cavolo-romanesco', 'it', 1.0, 'system'),
  ('romanesco', 'romanesco', 'cavolo-romanesco', 'it', 1.0, 'system'),
  ('cavolo-cappuccio', 'cavolo-cappuccio', 'cavolo-cappuccio', 'it', 1.0, 'system'),
  ('cavolo cappuccio', 'cavolo cappuccio', 'cavolo-cappuccio', 'it', 1.0, 'system'),
  ('verze', 'verze', 'cavolo-verza', 'it', 1.0, 'system'),
  ('verza', 'verza', 'cavolo-verza', 'it', 1.0, 'system'),
  ('cavolo-verza', 'cavolo-verza', 'cavolo-verza', 'it', 1.0, 'system'),
  ('cavolo-nero', 'cavolo-nero', 'cavolo-nero', 'it', 1.0, 'system'),
  ('cavolo nero', 'cavolo nero', 'cavolo-nero', 'it', 1.0, 'system'),
  ('cavolo-riccio', 'cavolo-riccio', 'cavolo-riccio-kale', 'it', 1.0, 'system'),
  ('kale', 'kale', 'cavolo-riccio-kale', 'it', 1.0, 'system'),
  ('cavolo riccio', 'cavolo riccio', 'cavolo-riccio-kale', 'it', 1.0, 'system'),
  ('cavolo-rosso', 'cavolo-rosso', 'cavolo-rosso', 'it', 1.0, 'system'),
  ('cavolo rosso', 'cavolo rosso', 'cavolo-rosso', 'it', 1.0, 'system'),
  ('cavolini-di-bruxelles', 'cavolini-di-bruxelles', 'cavolini-di-bruxelles', 'it', 1.0, 'system'),
  ('cavolini di bruxelles', 'cavolini di bruxelles', 'cavolini-di-bruxelles', 'it', 1.0, 'system'),
  ('cavoletti di bruxelles', 'cavoletti di bruxelles', 'cavolini-di-bruxelles', 'it', 1.0, 'system'),
  ('cime-di-rapa', 'cime-di-rapa', 'cime-di-rapa', 'it', 1.0, 'system'),
  ('cime di rapa', 'cime di rapa', 'cime-di-rapa', 'it', 1.0, 'system'),
  ('broccoletti', 'broccoletti', 'cime-di-rapa', 'it', 1.0, 'system'),
  ('cavolo-rapa', 'cavolo-rapa', 'cavolo-rapa-kohlrabi', 'it', 1.0, 'system'),
  ('kohlrabi', 'kohlrabi', 'cavolo-rapa-kohlrabi', 'it', 1.0, 'system'),
  ('cavolo-cinese', 'cavolo-cinese', 'cavolo-cinese-pak-choi', 'it', 1.0, 'system'),
  ('pak-choi', 'pak-choi', 'cavolo-cinese-pak-choi', 'it', 1.0, 'system'),
  ('pak choi', 'pak choi', 'cavolo-cinese-pak-choi', 'it', 1.0, 'system'),
  ('fagiolini', 'fagiolini', 'fagiolino', 'it', 1.0, 'system'),
  ('fagiolino', 'fagiolino', 'fagiolino', 'it', 1.0, 'system'),
  ('fagioli-secchi', 'fagioli-secchi', 'fagiolo-secco', 'it', 1.0, 'system'),
  ('fagiolo secco', 'fagiolo secco', 'fagiolo-secco', 'it', 1.0, 'system'),
  ('piselli-mangiatutto', 'piselli-mangiatutto', 'pisello-mangiatutto', 'it', 1.0, 'system'),
  ('pisello mangiatutto', 'pisello mangiatutto', 'pisello-mangiatutto', 'it', 1.0, 'system'),
  ('taccole', 'taccole', 'pisello-mangiatutto', 'it', 1.0, 'system'),
  ('fave', 'fave', 'fava', 'it', 1.0, 'system'),
  ('fava', 'fava', 'fava', 'it', 1.0, 'system'),
  ('ceci', 'ceci', 'ceci', 'it', 1.0, 'system'),
  ('cece', 'cece', 'ceci', 'it', 1.0, 'system'),
  ('lenticchie', 'lenticchie', 'lenticchia', 'it', 1.0, 'system'),
  ('lenticchia', 'lenticchia', 'lenticchia', 'it', 1.0, 'system'),
  ('lupini', 'lupini', 'lupino', 'it', 1.0, 'system'),
  ('lupino', 'lupino', 'lupino', 'it', 1.0, 'system'),
  ('cicerchie', 'cicerchie', 'cicerchia', 'it', 1.0, 'system'),
  ('cicerchia', 'cicerchia', 'cicerchia', 'it', 1.0, 'system'),
  ('soia', 'soia', 'soia', 'it', 1.0, 'system'),
  ('soja', 'soja', 'soia', 'it', 1.0, 'system'),
  ('taccole', 'taccole', 'taccole', 'it', 1.0, 'system'),
  ('taccola', 'taccola', 'taccole', 'it', 1.0, 'system'),
  ('maggiorane', 'maggiorane', 'maggiorana', 'it', 1.0, 'system'),
  ('maggiorana', 'maggiorana', 'maggiorana', 'it', 1.0, 'system'),
  ('alloro', 'alloro', 'alloro', 'it', 1.0, 'system'),
  ('lauro', 'lauro', 'alloro', 'it', 1.0, 'system'),
  ('coriandoli', 'coriandoli', 'coriandolo', 'it', 1.0, 'system'),
  ('coriandolo', 'coriandolo', 'coriandolo', 'it', 1.0, 'system'),
  ('aneti', 'aneti', 'aneto', 'it', 1.0, 'system'),
  ('aneto', 'aneto', 'aneto', 'it', 1.0, 'system'),
  ('finocchietto', 'finocchietto', 'finocchietto-selvatico', 'it', 1.0, 'system'),
  ('finocchietto-selvatico', 'finocchietto-selvatico', 'finocchietto-selvatico', 'it', 1.0, 'system'),
  ('santoreggie', 'santoreggie', 'santoreggia', 'it', 1.0, 'system'),
  ('santoreggia', 'santoreggia', 'santoreggia', 'it', 1.0, 'system'),
  ('melisse', 'melisse', 'melissa', 'it', 1.0, 'system'),
  ('melissa', 'melissa', 'melissa', 'it', 1.0, 'system'),
  ('erba-luigia', 'erba-luigia', 'erba-luigia-cedrina', 'it', 1.0, 'system'),
  ('cedrina', 'cedrina', 'erba-luigia-cedrina', 'it', 1.0, 'system'),
  ('erba luigia', 'erba luigia', 'erba-luigia-cedrina', 'it', 1.0, 'system'),
  ('dragoncelli', 'dragoncelli', 'dragoncello', 'it', 1.0, 'system'),
  ('dragoncello', 'dragoncello', 'dragoncello', 'it', 1.0, 'system'),
  ('estragone', 'estragone', 'dragoncello', 'it', 1.0, 'system'),
  ('rute', 'rute', 'ruta', 'it', 1.0, 'system'),
  ('ruta', 'ruta', 'ruta', 'it', 1.0, 'system'),
  ('borragini', 'borragini', 'borragine', 'it', 1.0, 'system'),
  ('borragine', 'borragine', 'borragine', 'it', 1.0, 'system'),
  ('calendule', 'calendule', 'calendula-edibile', 'it', 1.0, 'system'),
  ('calendula', 'calendula', 'calendula-edibile', 'it', 1.0, 'system'),
  ('nasturzi', 'nasturzi', 'nasturzio-edibile', 'it', 1.0, 'system'),
  ('nasturzio', 'nasturzio', 'nasturzio-edibile', 'it', 1.0, 'system'),
  ('camomille', 'camomille', 'camomilla', 'it', 1.0, 'system'),
  ('camomilla', 'camomilla', 'camomilla', 'it', 1.0, 'system'),
  ('zafferani', 'zafferani', 'zafferano', 'it', 1.0, 'system'),
  ('zafferano', 'zafferano', 'zafferano', 'it', 1.0, 'system'),
  ('capperi', 'capperi', 'cappero', 'it', 1.0, 'system'),
  ('cappero', 'cappero', 'cappero', 'it', 1.0, 'system'),
  ('gelsi', 'gelsi', 'gelso', 'it', 1.0, 'system'),
  ('gelso', 'gelso', 'gelso', 'it', 1.0, 'system'),
  ('giuggioli', 'giuggioli', 'giuggiolo', 'it', 1.0, 'system'),
  ('giuggiolo', 'giuggiolo', 'giuggiolo', 'it', 1.0, 'system'),
  ('corbezzoli', 'corbezzoli', 'corbezzolo', 'it', 1.0, 'system'),
  ('corbezzolo', 'corbezzolo', 'corbezzolo', 'it', 1.0, 'system'),
  ('mirti', 'mirti', 'mirto', 'it', 1.0, 'system'),
  ('mirto', 'mirto', 'mirto', 'it', 1.0, 'system'),
  ('sorbi', 'sorbi', 'sorbo-domestico', 'it', 1.0, 'system'),
  ('sorbo', 'sorbo', 'sorbo-domestico', 'it', 1.0, 'system'),
  ('azzaroli', 'azzaroli', 'azzarolo', 'it', 1.0, 'system'),
  ('azzarolo', 'azzarolo', 'azzarolo', 'it', 1.0, 'system'),
  ('carrubi', 'carrubi', 'carrubo', 'it', 1.0, 'system'),
  ('carrubo', 'carrubo', 'carrubo', 'it', 1.0, 'system'),
  ('alchechengi', 'alchechengi', 'alchechengi', 'it', 1.0, 'system'),
  ('physalis', 'physalis', 'alchechengi', 'it', 1.0, 'system'),
  ('sambuchi', 'sambuchi', 'sambuco', 'it', 1.0, 'system'),
  ('sambuco', 'sambuco', 'sambuco', 'it', 1.0, 'system'),
  ('cornioli', 'cornioli', 'corniolo', 'it', 1.0, 'system'),
  ('corniolo', 'corniolo', 'corniolo', 'it', 1.0, 'system'),
  ('prugnoli', 'prugnoli', 'prugnolo', 'it', 1.0, 'system'),
  ('prugnolo', 'prugnolo', 'prugnolo', 'it', 1.0, 'system'),
  ('more', 'more', 'mora', 'it', 1.0, 'system'),
  ('mora', 'mora', 'mora', 'it', 1.0, 'system'),
  ('ribes', 'ribes', 'ribes-rosso', 'it', 1.0, 'system'),
  ('ribes-rosso', 'ribes-rosso', 'ribes-rosso', 'it', 1.0, 'system'),
  ('ribes-nero', 'ribes-nero', 'ribes-nero', 'it', 1.0, 'system'),
  ('ribes nero', 'ribes nero', 'ribes-nero', 'it', 1.0, 'system'),
  ('uva-spina', 'uva-spina', 'uva-spina', 'it', 1.0, 'system'),
  ('uva spina', 'uva spina', 'uva-spina', 'it', 1.0, 'system'),
  ('fragoline-di-bosco', 'fragoline-di-bosco', 'fragolina-di-bosco', 'it', 1.0, 'system'),
  ('fragolina di bosco', 'fragolina di bosco', 'fragolina-di-bosco', 'it', 1.0, 'system'),
  ('pomodori', 'pomodori', 'pomodoro', 'it', 1.0, 'system'),
  ('peperoncini', 'peperoncini', 'peperoncino', 'it', 1.0, 'system'),
  ('zucchine', 'zucchine', 'zucchina', 'it', 1.0, 'system'),
  ('melanzane', 'melanzane', 'melanzana', 'it', 1.0, 'system'),
  ('lattuge', 'lattuge', 'lattuga', 'it', 1.0, 'system'),
  ('basilici', 'basilici', 'basilico', 'it', 1.0, 'system'),
  ('fagioli', 'fagioli', 'fagiolo', 'it', 1.0, 'system'),
  ('piselli', 'piselli', 'pisello', 'it', 1.0, 'system'),
  ('carote', 'carote', 'carota', 'it', 1.0, 'system'),
  ('cipolle', 'cipolle', 'cipolla', 'it', 1.0, 'system'),
  ('patate', 'patate', 'patata', 'it', 1.0, 'system'),
  ('radicchii', 'radicchii', 'radicchio', 'it', 1.0, 'system'),
  ('spinacii', 'spinacii', 'spinacio', 'it', 1.0, 'system'),
  ('finocchii', 'finocchii', 'finocchio', 'it', 1.0, 'system'),
  ('frumenti', 'frumenti', 'frumento', 'it', 1.0, 'system'),
  ('rosmarini', 'rosmarini', 'rosmarino', 'it', 1.0, 'system'),
  ('salvie', 'salvie', 'salvia', 'it', 1.0, 'system'),
  ('timi', 'timi', 'timo', 'it', 1.0, 'system'),
  ('origani', 'origani', 'origano', 'it', 1.0, 'system'),
  ('mente', 'mente', 'menta', 'it', 1.0, 'system'),
  ('lavande', 'lavande', 'lavanda', 'it', 1.0, 'system'),
  ('zucce', 'zucce', 'zucca', 'it', 1.0, 'system'),
  ('cetrioli', 'cetrioli', 'cetriolo', 'it', 1.0, 'system'),
  ('melonei', 'melonei', 'melone', 'it', 1.0, 'system'),
  ('angurie', 'angurie', 'anguria', 'it', 1.0, 'system'),
  ('peperone dolcei', 'peperone dolcei', 'peperone-dolce', 'it', 1.0, 'system'),
  ('aglii', 'aglii', 'aglio', 'it', 1.0, 'system'),
  ('porri', 'porri', 'porro', 'it', 1.0, 'system'),
  ('scalogni', 'scalogni', 'scalogno', 'it', 1.0, 'system'),
  ('barbabietola rosse', 'barbabietola rosse', 'barbabietola-rossa', 'it', 1.0, 'system'),
  ('rape', 'rape', 'rapa', 'it', 1.0, 'system'),
  ('ravanelli', 'ravanelli', 'ravanello', 'it', 1.0, 'system'),
  ('sedani', 'sedani', 'sedano', 'it', 1.0, 'system'),
  ('sedano rape', 'sedano rape', 'sedano-rapa', 'it', 1.0, 'system'),
  ('prezzemoli', 'prezzemoli', 'prezzemolo', 'it', 1.0, 'system'),
  ('carciofi', 'carciofi', 'carciofo', 'it', 1.0, 'system'),
  ('asparagi', 'asparagi', 'asparago', 'it', 1.0, 'system'),
  ('rucole', 'rucole', 'rucola', 'it', 1.0, 'system'),
  ('pastinace', 'pastinace', 'pastinaca', 'it', 1.0, 'system'),
  ('patata dolcei', 'patata dolcei', 'patata-dolce', 'it', 1.0, 'system'),
  ('erba cipolline', 'erba cipolline', 'erba-cipollina', 'it', 1.0, 'system'),
  ('lattuga romane', 'lattuga romane', 'lattuga-romana', 'it', 1.0, 'system'),
  ('indivia riccie', 'indivia riccie', 'indivia-riccia', 'it', 1.0, 'system'),
  ('scarole', 'scarole', 'scarola', 'it', 1.0, 'system'),
  ('cicorie', 'cicorie', 'cicoria', 'it', 1.0, 'system'),
  ('catalogne', 'catalogne', 'catalogna', 'it', 1.0, 'system'),
  ('puntarellei', 'puntarellei', 'puntarelle', 'it', 1.0, 'system'),
  ('radicchio variegato castelfranci', 'radicchio variegato castelfranci', 'radicchio-variegato-castelfranco', 'it', 1.0, 'system'),
  ('bietola da coste', 'bietola da coste', 'bietola-da-costa', 'it', 1.0, 'system'),
  ('bietola da taglii', 'bietola da taglii', 'bietola-da-taglio', 'it', 1.0, 'system'),
  ('spinacio neozelandesei', 'spinacio neozelandesei', 'spinacio-neozelandese', 'it', 1.0, 'system'),
  ('crescionei', 'crescionei', 'crescione', 'it', 1.0, 'system'),
  ('portulace', 'portulace', 'portulaca', 'it', 1.0, 'system'),
  ('cavolfiorei', 'cavolfiorei', 'cavolfiore', 'it', 1.0, 'system'),
  ('broccoli', 'broccoli', 'broccolo', 'it', 1.0, 'system'),
  ('cavolo romanesci', 'cavolo romanesci', 'cavolo-romanesco', 'it', 1.0, 'system'),
  ('cavolo cappuccii', 'cavolo cappuccii', 'cavolo-cappuccio', 'it', 1.0, 'system'),
  ('cavolo verze', 'cavolo verze', 'cavolo-verza', 'it', 1.0, 'system'),
  ('cavolo neri', 'cavolo neri', 'cavolo-nero', 'it', 1.0, 'system'),
  ('cavolo rossi', 'cavolo rossi', 'cavolo-rosso', 'it', 1.0, 'system'),
  ('cime di rape', 'cime di rape', 'cime-di-rapa', 'it', 1.0, 'system'),
  ('broccolo spigarielli', 'broccolo spigarielli', 'broccolo-spigariello', 'it', 1.0, 'system'),
  ('fagiolini', 'fagiolini', 'fagiolino', 'it', 1.0, 'system'),
  ('fagiolo secci', 'fagiolo secci', 'fagiolo-secco', 'it', 1.0, 'system'),
  ('pisello mangiatutti', 'pisello mangiatutti', 'pisello-mangiatutto', 'it', 1.0, 'system'),
  ('fave', 'fave', 'fava', 'it', 1.0, 'system'),
  ('lenticchie', 'lenticchie', 'lenticchia', 'it', 1.0, 'system'),
  ('lupini', 'lupini', 'lupino', 'it', 1.0, 'system'),
  ('cicerchie', 'cicerchie', 'cicerchia', 'it', 1.0, 'system'),
  ('soie', 'soie', 'soia', 'it', 1.0, 'system'),
  ('taccolei', 'taccolei', 'taccole', 'it', 1.0, 'system'),
  ('maggiorane', 'maggiorane', 'maggiorana', 'it', 1.0, 'system'),
  ('allori', 'allori', 'alloro', 'it', 1.0, 'system'),
  ('coriandoli', 'coriandoli', 'coriandolo', 'it', 1.0, 'system'),
  ('aneti', 'aneti', 'aneto', 'it', 1.0, 'system'),
  ('finocchietto selvatici', 'finocchietto selvatici', 'finocchietto-selvatico', 'it', 1.0, 'system'),
  ('santoreggie', 'santoreggie', 'santoreggia', 'it', 1.0, 'system'),
  ('melisse', 'melisse', 'melissa', 'it', 1.0, 'system'),
  ('dragoncelli', 'dragoncelli', 'dragoncello', 'it', 1.0, 'system'),
  ('rute', 'rute', 'ruta', 'it', 1.0, 'system'),
  ('borraginei', 'borraginei', 'borragine', 'it', 1.0, 'system'),
  ('calendula edibilei', 'calendula edibilei', 'calendula-edibile', 'it', 1.0, 'system'),
  ('nasturzio edibilei', 'nasturzio edibilei', 'nasturzio-edibile', 'it', 1.0, 'system'),
  ('camomille', 'camomille', 'camomilla', 'it', 1.0, 'system'),
  ('zafferani', 'zafferani', 'zafferano', 'it', 1.0, 'system'),
  ('capperi', 'capperi', 'cappero', 'it', 1.0, 'system'),
  ('cardi', 'cardi', 'cardo', 'it', 1.0, 'system'),
  ('scorzonere', 'scorzonere', 'scorzonera', 'it', 1.0, 'system'),
  ('salsefrice', 'salsefrice', 'salsefrica', 'it', 1.0, 'system'),
  ('rafani', 'rafani', 'rafano', 'it', 1.0, 'system'),
  ('fragola di bosci', 'fragola di bosci', 'fragola-bosco', 'it', 1.0, 'system'),
  ('fragola elsante', 'fragola elsante', 'fragola-elsanta', 'it', 1.0, 'system'),
  ('fragola seascapei', 'fragola seascapei', 'fragola-seascape', 'it', 1.0, 'system'),
  ('fragola candonge', 'fragola candonge', 'fragola-candonga', 'it', 1.0, 'system'),
  ('fragola matere', 'fragola matere', 'fragola-matera', 'it', 1.0, 'system'),
  ('fragola sabrine', 'fragola sabrine', 'fragola-sabrina', 'it', 1.0, 'system'),
  ('fragola albe', 'fragola albe', 'fragola-alba', 'it', 1.0, 'system'),
  ('fragola florencei', 'fragola florencei', 'fragola-florence', 'it', 1.0, 'system'),
  ('fragola gariguettei', 'fragola gariguettei', 'fragola-gariguette', 'it', 1.0, 'system'),
  ('fragola malge', 'fragola malge', 'fragola-malga', 'it', 1.0, 'system'),
  ('fragola roxane', 'fragola roxane', 'fragola-roxana', 'it', 1.0, 'system'),
  ('fragola sirie', 'fragola sirie', 'fragola-siria', 'it', 1.0, 'system'),
  ('fragolina di bosci', 'fragolina di bosci', 'fragolina-di-bosco', 'it', 1.0, 'system'),
  ('pesco pesca gialle', 'pesco pesca gialle', 'pesco-gialla', 'it', 1.0, 'system'),
  ('ciliegio duronei', 'ciliegio duronei', 'ciliegio-durone', 'it', 1.0, 'system'),
  ('cotogni', 'cotogni', 'cotogno', 'it', 1.0, 'system'),
  ('nespolo del giapponei', 'nespolo del giapponei', 'nespolo-del-giappone', 'it', 1.0, 'system'),
  ('nespolo comunei', 'nespolo comunei', 'nespolo-comune', 'it', 1.0, 'system'),
  ('nettarini', 'nettarini', 'nettarino', 'it', 1.0, 'system'),
  ('albicocci', 'albicocci', 'albicocco', 'it', 1.0, 'system'),
  ('susini', 'susini', 'susino', 'it', 1.0, 'system'),
  ('mandorli', 'mandorli', 'mandorlo', 'it', 1.0, 'system'),
  ('noccioli', 'noccioli', 'nocciolo', 'it', 1.0, 'system'),
  ('nocei', 'nocei', 'noce', 'it', 1.0, 'system'),
  ('castagni', 'castagni', 'castagno', 'it', 1.0, 'system'),
  ('pistacchii', 'pistacchii', 'pistacchio', 'it', 1.0, 'system'),
  ('fici', 'fici', 'fico', 'it', 1.0, 'system'),
  ('fico d''indie', 'fico d''indie', 'fico-dindia', 'it', 1.0, 'system'),
  ('melograni', 'melograni', 'melograno', 'it', 1.0, 'system'),
  ('uva da tavole', 'uva da tavole', 'uva-da-tavola', 'it', 1.0, 'system'),
  ('limonei', 'limonei', 'limone', 'it', 1.0, 'system'),
  ('arancio dolcei', 'arancio dolcei', 'arancio-dolce', 'it', 1.0, 'system'),
  ('arancio amari', 'arancio amari', 'arancio-amaro', 'it', 1.0, 'system'),
  ('mandarini', 'mandarini', 'mandarino', 'it', 1.0, 'system'),
  ('clementini', 'clementini', 'clementino', 'it', 1.0, 'system'),
  ('bergamotti', 'bergamotti', 'bergamotto', 'it', 1.0, 'system'),
  ('pompelmi', 'pompelmi', 'pompelmo', 'it', 1.0, 'system'),
  ('cedri', 'cedri', 'cedro', 'it', 1.0, 'system'),
  ('limei', 'limei', 'lime', 'it', 1.0, 'system'),
  ('chinotti', 'chinotti', 'chinotto', 'it', 1.0, 'system'),
  ('melo gale', 'melo gale', 'melo-gala', 'it', 1.0, 'system'),
  ('melo renette', 'melo renette', 'melo-renetta', 'it', 1.0, 'system'),
  ('pero conferencei', 'pero conferencei', 'pero-conference', 'it', 1.0, 'system'),
  ('pero decana del comizii', 'pero decana del comizii', 'pero-decana-del-comizio', 'it', 1.0, 'system'),
  ('pero coscie', 'pero coscie', 'pero-coscia', 'it', 1.0, 'system'),
  ('olivo frantoii', 'olivo frantoii', 'olivo-frantoio', 'it', 1.0, 'system'),
  ('olivo leccini', 'olivo leccini', 'olivo-leccino', 'it', 1.0, 'system'),
  ('olivo moraioli', 'olivo moraioli', 'olivo-moraiolo', 'it', 1.0, 'system'),
  ('olivo pendolini', 'olivo pendolini', 'olivo-pendolino', 'it', 1.0, 'system'),
  ('vite sangiovesei', 'vite sangiovesei', 'vite-sangiovese', 'it', 1.0, 'system'),
  ('vite nebbioli', 'vite nebbioli', 'vite-nebbiolo', 'it', 1.0, 'system'),
  ('vite barbere', 'vite barbere', 'vite-barbera', 'it', 1.0, 'system'),
  ('vite montepulciani', 'vite montepulciani', 'vite-montepulciano', 'it', 1.0, 'system'),
  ('vite trebbiani', 'vite trebbiani', 'vite-trebbiano', 'it', 1.0, 'system'),
  ('vite pinot grigii', 'vite pinot grigii', 'vite-pinot-grigio', 'it', 1.0, 'system'),
  ('papaye', 'papaye', 'papaya-comune', 'it', 1.0, 'system'),
  ('banano nani', 'banano nani', 'banano-nano', 'it', 1.0, 'system'),
  ('gelsi', 'gelsi', 'gelso', 'it', 1.0, 'system'),
  ('giuggioli', 'giuggioli', 'giuggiolo', 'it', 1.0, 'system'),
  ('corbezzoli', 'corbezzoli', 'corbezzolo', 'it', 1.0, 'system'),
  ('mirti', 'mirti', 'mirto', 'it', 1.0, 'system'),
  ('sorbo domestici', 'sorbo domestici', 'sorbo-domestico', 'it', 1.0, 'system'),
  ('azzaroli', 'azzaroli', 'azzarolo', 'it', 1.0, 'system'),
  ('carrubi', 'carrubi', 'carrubo', 'it', 1.0, 'system'),
  ('sambuci', 'sambuci', 'sambuco', 'it', 1.0, 'system'),
  ('cornioli', 'cornioli', 'corniolo', 'it', 1.0, 'system'),
  ('prugnoli', 'prugnoli', 'prugnolo', 'it', 1.0, 'system'),
  ('lampone glen amplei', 'lampone glen amplei', 'lampone-glen-ample', 'it', 1.0, 'system'),
  ('lampone heritagei', 'lampone heritagei', 'lampone-heritage', 'it', 1.0, 'system'),
  ('more', 'more', 'mora', 'it', 1.0, 'system'),
  ('mirtilli', 'mirtilli', 'mirtillo', 'it', 1.0, 'system'),
  ('ribes rossi', 'ribes rossi', 'ribes-rosso', 'it', 1.0, 'system'),
  ('ribes neri', 'ribes neri', 'ribes-nero', 'it', 1.0, 'system'),
  ('uva spine', 'uva spine', 'uva-spina', 'it', 1.0, 'system')
ON CONFLICT (synonym, locale) DO NOTHING;

