import test from 'node:test'
import assert from 'node:assert/strict'

import { HistoricalComparisonService } from '@/services/historicalComparisonService'
import type { QualityResult } from '@/types'
import type {
  HistoricalComparisonRequest,
  PrescriptionExecutionRecord,
  PrescriptionMap,
} from '@/types/prescriptionMaps'

const buildMap = (
  id: string,
  name: string,
  generationDate: string,
  rates: [number, number],
  costSavings: number,
  inputReduction: number
): PrescriptionMap => ({
  id,
  gardenId: 'garden-1',
  gardenName: 'Vigneto Collina',
  name,
  mapType: 'treatment',
  generationDate,
  dataSourcePeriod: { startDate: '2025-01-01', endDate: generationDate.slice(0, 10) },
  dataSources: {
    ndviData: true,
    plantLevelData: true,
    rowLevelData: true,
    soilData: true,
    weatherData: true,
  },
  zones: [
    {
      id: `${id}-north`,
      prescriptionMapId: id,
      zoneNumber: 1,
      zoneName: 'Blocco Nord',
      zoneType: 'variable',
      geometry: { type: 'Polygon', coordinates: [] },
      centroid: { latitude: 41.1, longitude: 14.1 },
      areaSqm: 5000,
      prescription: {
        applicationRate: rates[0],
        unit: 'L/ha',
        applicationMethod: 'variable_rate',
        expectedOutcome: { yieldIncrease: 24 },
      },
      sourceData: {},
      dataQuality: 88,
      confidence: 86,
      createdAt: generationDate,
      updatedAt: generationDate,
    },
    {
      id: `${id}-south`,
      prescriptionMapId: id,
      zoneNumber: 2,
      zoneName: 'Blocco Sud',
      zoneType: 'variable',
      geometry: { type: 'Polygon', coordinates: [] },
      centroid: { latitude: 41.2, longitude: 14.2 },
      areaSqm: 5000,
      prescription: {
        applicationRate: rates[1],
        unit: 'L/ha',
        applicationMethod: 'variable_rate',
        expectedOutcome: { yieldIncrease: 20 },
      },
      sourceData: {},
      dataQuality: 84,
      confidence: 82,
      createdAt: generationDate,
      updatedAt: generationDate,
    },
  ],
  totalZones: 2,
  totalAreaSqm: 10000,
  exportFormats: { shapefile: true, kml: true, isoxml: false, geojson: true, csv: true },
  areaHectares: 1,
  zonesCount: 2,
  applicationRate: { min: Math.min(...rates), max: Math.max(...rates), unit: 'L/ha' },
  costSavings,
  inputReduction,
  status: 'completed',
  validationStatus: 'valid',
  qualityScore: 87,
  dataCompleteness: 91,
  createdAt: generationDate,
  updatedAt: generationDate,
})

const mapA = buildMap('map-a', 'Strategia Primavera', '2025-03-10T08:00:00.000Z', [80, 90], 110, 6)
const mapB = buildMap('map-b', 'Strategia Estate', '2025-07-12T08:00:00.000Z', [95, 100], 145, 9)
const mapC = buildMap('map-c', 'Strategia Autunno', '2025-10-08T08:00:00.000Z', [105, 112], 190, 12)

const executionRecords: PrescriptionExecutionRecord[] = [
  {
    id: 'rec-a-north',
    prescriptionMapId: mapA.id,
    prescriptionZoneId: `${mapA.id}-north`,
    applicationDate: '2025-03-12T08:00:00.000Z',
    productName: 'Trattamento A',
    productType: 'treatment',
    plannedRate: 80,
    actualRate: 76,
    unit: 'L/ha',
    plannedAreaSqm: 5000,
    areaAppliedSqm: 4200,
    totalProductUsed: 31.92,
    applicationAccuracy: 82,
    executionStatus: 'partial',
    executionScopeType: 'zone',
    executionScopeId: `${mapA.id}-north`,
    sourceOperationType: 'manual',
    createdAt: '2025-03-12T08:00:00.000Z',
    updatedAt: '2025-03-12T08:00:00.000Z',
  },
  {
    id: 'rec-a-south',
    prescriptionMapId: mapA.id,
    prescriptionZoneId: `${mapA.id}-south`,
    applicationDate: '2025-03-12T08:00:00.000Z',
    productName: 'Trattamento A',
    productType: 'treatment',
    plannedRate: 90,
    actualRate: 80,
    unit: 'L/ha',
    plannedAreaSqm: 5000,
    areaAppliedSqm: 3800,
    totalProductUsed: 30.4,
    applicationAccuracy: 74,
    executionStatus: 'partial',
    executionScopeType: 'zone',
    executionScopeId: `${mapA.id}-south`,
    sourceOperationType: 'manual',
    createdAt: '2025-03-12T08:00:00.000Z',
    updatedAt: '2025-03-12T08:00:00.000Z',
  },
  {
    id: 'rec-b-north',
    prescriptionMapId: mapB.id,
    prescriptionZoneId: `${mapB.id}-north`,
    applicationDate: '2025-07-14T08:00:00.000Z',
    productName: 'Trattamento B',
    productType: 'treatment',
    plannedRate: 95,
    actualRate: 95,
    unit: 'L/ha',
    plannedAreaSqm: 5000,
    areaAppliedSqm: 5000,
    totalProductUsed: 47.5,
    applicationAccuracy: 100,
    executionStatus: 'completed',
    executionScopeType: 'zone',
    executionScopeId: `${mapB.id}-north`,
    sourceOperationType: 'manual',
    createdAt: '2025-07-14T08:00:00.000Z',
    updatedAt: '2025-07-14T08:00:00.000Z',
  },
  {
    id: 'rec-b-south',
    prescriptionMapId: mapB.id,
    prescriptionZoneId: `${mapB.id}-south`,
    applicationDate: '2025-07-14T08:00:00.000Z',
    productName: 'Trattamento B',
    productType: 'treatment',
    plannedRate: 100,
    actualRate: 96,
    unit: 'L/ha',
    plannedAreaSqm: 5000,
    areaAppliedSqm: 4700,
    totalProductUsed: 45.12,
    applicationAccuracy: 92,
    executionStatus: 'completed',
    executionScopeType: 'zone',
    executionScopeId: `${mapB.id}-south`,
    sourceOperationType: 'manual',
    createdAt: '2025-07-14T08:00:00.000Z',
    updatedAt: '2025-07-14T08:00:00.000Z',
  },
  {
    id: 'rec-c-north',
    prescriptionMapId: mapC.id,
    prescriptionZoneId: `${mapC.id}-north`,
    applicationDate: '2025-10-10T08:00:00.000Z',
    productName: 'Trattamento C',
    productType: 'treatment',
    plannedRate: 105,
    actualRate: 106,
    unit: 'L/ha',
    plannedAreaSqm: 5000,
    areaAppliedSqm: 5000,
    totalProductUsed: 53,
    applicationAccuracy: 99,
    executionStatus: 'completed',
    executionScopeType: 'zone',
    executionScopeId: `${mapC.id}-north`,
    sourceOperationType: 'manual',
    createdAt: '2025-10-10T08:00:00.000Z',
    updatedAt: '2025-10-10T08:00:00.000Z',
  },
  {
    id: 'rec-c-south',
    prescriptionMapId: mapC.id,
    prescriptionZoneId: `${mapC.id}-south`,
    applicationDate: '2025-10-10T08:00:00.000Z',
    productName: 'Trattamento C',
    productType: 'treatment',
    plannedRate: 112,
    actualRate: 111,
    unit: 'L/ha',
    plannedAreaSqm: 5000,
    areaAppliedSqm: 4950,
    totalProductUsed: 54.95,
    applicationAccuracy: 98,
    executionStatus: 'completed',
    executionScopeType: 'zone',
    executionScopeId: `${mapC.id}-south`,
    sourceOperationType: 'manual',
    createdAt: '2025-10-10T08:00:00.000Z',
    updatedAt: '2025-10-10T08:00:00.000Z',
  },
]

const qualityResults: QualityResult[] = [
  {
    id: 'quality-a-north',
    gardenId: 'garden-1',
    cropContextId: 'vineyard',
    scopeType: 'zone',
    scopeId: `${mapA.id}-north`,
    zoneId: `${mapA.id}-north`,
    recordedAt: '2025-03-18T08:00:00.000Z',
    source: 'manual',
    qualityGrade: 'fair',
    qualityScore: 48,
    marketableYieldKg: 18,
    defectIncidencePercentage: 24,
    createdAt: '2025-03-18T08:00:00.000Z',
    updatedAt: '2025-03-18T08:00:00.000Z',
  },
  {
    id: 'quality-a-south',
    gardenId: 'garden-1',
    cropContextId: 'vineyard',
    scopeType: 'zone',
    scopeId: `${mapA.id}-south`,
    zoneId: `${mapA.id}-south`,
    recordedAt: '2025-03-18T08:00:00.000Z',
    source: 'manual',
    qualityGrade: 'poor',
    qualityScore: 35,
    marketableYieldKg: 15,
    defectIncidencePercentage: 30,
    createdAt: '2025-03-18T08:00:00.000Z',
    updatedAt: '2025-03-18T08:00:00.000Z',
  },
  {
    id: 'quality-b-north',
    gardenId: 'garden-1',
    cropContextId: 'vineyard',
    scopeType: 'zone',
    scopeId: `${mapB.id}-north`,
    zoneId: `${mapB.id}-north`,
    recordedAt: '2025-07-20T08:00:00.000Z',
    source: 'manual',
    qualityGrade: 'good',
    qualityScore: 74,
    marketableYieldKg: 24,
    defectIncidencePercentage: 14,
    createdAt: '2025-07-20T08:00:00.000Z',
    updatedAt: '2025-07-20T08:00:00.000Z',
  },
  {
    id: 'quality-b-south',
    gardenId: 'garden-1',
    cropContextId: 'vineyard',
    scopeType: 'zone',
    scopeId: `${mapB.id}-south`,
    zoneId: `${mapB.id}-south`,
    recordedAt: '2025-07-20T08:00:00.000Z',
    source: 'manual',
    qualityGrade: 'good',
    qualityScore: 70,
    marketableYieldKg: 22,
    defectIncidencePercentage: 16,
    createdAt: '2025-07-20T08:00:00.000Z',
    updatedAt: '2025-07-20T08:00:00.000Z',
  },
  {
    id: 'quality-c-north',
    gardenId: 'garden-1',
    cropContextId: 'vineyard',
    scopeType: 'zone',
    scopeId: `${mapC.id}-north`,
    zoneId: `${mapC.id}-north`,
    recordedAt: '2025-10-16T08:00:00.000Z',
    source: 'manual',
    qualityGrade: 'excellent',
    qualityScore: 88,
    marketableYieldKg: 31,
    defectIncidencePercentage: 7,
    createdAt: '2025-10-16T08:00:00.000Z',
    updatedAt: '2025-10-16T08:00:00.000Z',
  },
  {
    id: 'quality-c-south',
    gardenId: 'garden-1',
    cropContextId: 'vineyard',
    scopeType: 'zone',
    scopeId: `${mapC.id}-south`,
    zoneId: `${mapC.id}-south`,
    recordedAt: '2025-10-16T08:00:00.000Z',
    source: 'manual',
    qualityGrade: 'excellent',
    qualityScore: 84,
    marketableYieldKg: 29,
    defectIncidencePercentage: 9,
    createdAt: '2025-10-16T08:00:00.000Z',
    updatedAt: '2025-10-16T08:00:00.000Z',
  },
]

test('HistoricalComparisonService performs real ledger-backed strategy comparison', async () => {
  const maps = new Map<string, PrescriptionMap>([
    [mapA.id, mapA],
    [mapB.id, mapB],
    [mapC.id, mapC],
  ])

  const provider = {
    getPrescriptionMap: async (id: string) => maps.get(id) ?? null,
    getPrescriptionExecutionRecords: async (prescriptionMapId: string) => (
      executionRecords.filter((record) => record.prescriptionMapId === prescriptionMapId)
    ),
    getQualityResults: async (_gardenId: string, filters?: { zoneId?: string }) => (
      qualityResults.filter((result) => !filters?.zoneId || result.zoneId === filters.zoneId)
    ),
    getGarden: async (id: string) => ({ id }),
  }

  const service = new HistoricalComparisonService(provider)
  const request: HistoricalComparisonRequest = {
    gardenId: 'garden-1',
    mapIds: [mapA.id, mapB.id, mapC.id],
    comparisonType: 'temporal',
    timeRange: {
      startDate: '2025-01-01',
      endDate: '2025-12-31',
    },
    analysisMetrics: ['application_rate', 'yield', 'cost', 'quality'],
  }

  const result = await service.performHistoricalComparison(request)

  assert.equal(result.success, true)
  assert.equal(result.temporalTrends.find((trend) => trend.metric === 'application_rate')?.trend, 'increasing')
  assert.equal(result.temporalTrends.find((trend) => trend.metric === 'yield')?.trend, 'increasing')
  assert.equal(result.zoneEvolution.length, 2)
  assert.equal(result.seasonalPatterns.length, 3)
  assert.equal(result.seasonalPatterns[result.seasonalPatterns.length - 1]?.season, 'autumn')
  assert.equal(result.treatmentResponse.length, 1)
  assert.equal(result.treatmentResponse[0]?.treatmentType, 'treatment')
  assert.equal(result.yieldCorrelation.correlationCoefficient > 0, true)
  assert.equal(result.insights.keyFindings.length > 0, true)
  assert.equal(result.insights.opportunities.some((entry) => entry.includes('benchmark')), true)
  assert.equal(result.quality.confidenceScore > 0, true)
})
