-- O41 / M15: auditable administrative billing and renewal for the single PRO version.

CREATE TABLE public.organization_commercial_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL UNIQUE REFERENCES public.organizations(id) ON DELETE CASCADE,
  product_version text NOT NULL DEFAULT 'PRO' CHECK (product_version = 'PRO'),
  status text NOT NULL DEFAULT 'PendingActivation'
    CHECK (status IN ('PendingActivation', 'AwaitingPayment', 'Active', 'PastDue', 'Suspended', 'Cancelled')),
  legal_name text NOT NULL,
  billing_email text NOT NULL,
  vat_number text,
  administrative_notes text,
  current_period_start date,
  current_period_end date,
  next_renewal_date date,
  submitted_by uuid NOT NULL REFERENCES auth.users(id),
  activated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.organization_invoices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  commercial_account_id uuid NOT NULL REFERENCES public.organization_commercial_accounts(id) ON DELETE RESTRICT,
  external_reference text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'Issued' CHECK (status IN ('Issued', 'Paid', 'Overdue', 'Void')),
  amount_cents bigint NOT NULL CHECK (amount_cents > 0),
  currency text NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  issued_on date NOT NULL,
  due_on date NOT NULL CHECK (due_on >= issued_on),
  paid_at timestamptz,
  period_start date NOT NULL,
  period_end date NOT NULL CHECK (period_end > period_start),
  issued_by uuid NOT NULL REFERENCES auth.users(id),
  payment_recorded_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.organization_commercial_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  actor_id uuid NOT NULL REFERENCES auth.users(id),
  event_type text NOT NULL CHECK (
    event_type IN ('BillingProfileSubmitted', 'InvoiceIssued', 'PaymentRecorded', 'ContractRenewed')
  ),
  invoice_id uuid REFERENCES public.organization_invoices(id) ON DELETE RESTRICT,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_organization_invoices_account
  ON public.organization_invoices(commercial_account_id, issued_on DESC);
CREATE INDEX idx_organization_commercial_audit
  ON public.organization_commercial_audit_log(organization_id, created_at DESC);
CREATE INDEX idx_organization_commercial_renewal
  ON public.organization_commercial_accounts(next_renewal_date)
  WHERE status = 'Active';

ALTER TABLE public.organization_commercial_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_commercial_audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Organization managers can view commercial account"
  ON public.organization_commercial_accounts FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.organizations o
      LEFT JOIN public.organization_members om
        ON om.organization_id = o.id
       AND om.user_id = auth.uid()
       AND om.status = 'Active'
      LEFT JOIN public.roles r ON r.id = om.role_id
      WHERE o.id = organization_commercial_accounts.organization_id
        AND (o.owner_id = auth.uid() OR r.name IN ('Owner', 'Administrator'))
    )
  );

CREATE POLICY "Organization managers can view invoices"
  ON public.organization_invoices FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.organization_commercial_accounts a
      JOIN public.organizations o ON o.id = a.organization_id
      LEFT JOIN public.organization_members om
        ON om.organization_id = o.id
       AND om.user_id = auth.uid()
       AND om.status = 'Active'
      LEFT JOIN public.roles r ON r.id = om.role_id
      WHERE a.id = organization_invoices.commercial_account_id
        AND (o.owner_id = auth.uid() OR r.name IN ('Owner', 'Administrator'))
    )
  );

CREATE POLICY "Organization managers can view commercial audit"
  ON public.organization_commercial_audit_log FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.organizations o
      LEFT JOIN public.organization_members om
        ON om.organization_id = o.id
       AND om.user_id = auth.uid()
       AND om.status = 'Active'
      LEFT JOIN public.roles r ON r.id = om.role_id
      WHERE o.id = organization_commercial_audit_log.organization_id
        AND (o.owner_id = auth.uid() OR r.name IN ('Owner', 'Administrator'))
    )
  );

CREATE OR REPLACE FUNCTION public.submit_pro_billing_profile(
  p_organization_id uuid,
  p_actor_id uuid,
  p_legal_name text,
  p_billing_email text,
  p_vat_number text DEFAULT NULL,
  p_administrative_notes text DEFAULT NULL
)
RETURNS public.organization_commercial_accounts
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  account public.organization_commercial_accounts;
  actor_can_manage boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM public.organizations o
    LEFT JOIN public.organization_members om
      ON om.organization_id = o.id
     AND om.user_id = p_actor_id
     AND om.status = 'Active'
    LEFT JOIN public.roles r ON r.id = om.role_id
    WHERE o.id = p_organization_id
      AND (o.owner_id = p_actor_id OR r.name IN ('Owner', 'Administrator'))
  ) INTO actor_can_manage;

  IF NOT actor_can_manage THEN
    RAISE EXCEPTION 'billing_manager_required';
  END IF;
  IF NULLIF(btrim(p_legal_name), '') IS NULL THEN
    RAISE EXCEPTION 'legal_name_required';
  END IF;
  IF NULLIF(btrim(p_billing_email), '') IS NULL THEN
    RAISE EXCEPTION 'billing_email_required';
  END IF;

  INSERT INTO public.organization_commercial_accounts (
    organization_id,
    legal_name,
    billing_email,
    vat_number,
    administrative_notes,
    submitted_by
  )
  VALUES (
    p_organization_id,
    btrim(p_legal_name),
    lower(btrim(p_billing_email)),
    NULLIF(btrim(p_vat_number), ''),
    NULLIF(btrim(p_administrative_notes), ''),
    p_actor_id
  )
  ON CONFLICT (organization_id) DO UPDATE SET
    legal_name = EXCLUDED.legal_name,
    billing_email = EXCLUDED.billing_email,
    vat_number = EXCLUDED.vat_number,
    administrative_notes = EXCLUDED.administrative_notes,
    submitted_by = EXCLUDED.submitted_by,
    updated_at = now()
  RETURNING * INTO account;

  INSERT INTO public.organization_commercial_audit_log (
    organization_id, actor_id, event_type, details
  )
  VALUES (
    p_organization_id,
    p_actor_id,
    'BillingProfileSubmitted',
    jsonb_build_object('commercialAccountId', account.id, 'productVersion', 'PRO')
  );

  RETURN account;
END;
$$;

CREATE OR REPLACE FUNCTION public.issue_pro_invoice(
  p_organization_id uuid,
  p_actor_id uuid,
  p_external_reference text,
  p_amount_cents bigint,
  p_currency text,
  p_issued_on date,
  p_due_on date,
  p_period_start date,
  p_period_end date
)
RETURNS public.organization_invoices
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  account public.organization_commercial_accounts;
  invoice public.organization_invoices;
BEGIN
  SELECT * INTO account
  FROM public.organization_commercial_accounts
  WHERE organization_id = p_organization_id
  FOR UPDATE;

  IF account.id IS NULL THEN
    RAISE EXCEPTION 'billing_profile_required';
  END IF;

  INSERT INTO public.organization_invoices (
    commercial_account_id,
    external_reference,
    amount_cents,
    currency,
    issued_on,
    due_on,
    period_start,
    period_end,
    issued_by
  )
  VALUES (
    account.id,
    btrim(p_external_reference),
    p_amount_cents,
    upper(btrim(p_currency)),
    p_issued_on,
    p_due_on,
    p_period_start,
    p_period_end,
    p_actor_id
  )
  RETURNING * INTO invoice;

  UPDATE public.organization_commercial_accounts
  SET status = 'AwaitingPayment', updated_at = now()
  WHERE id = account.id;

  INSERT INTO public.organization_commercial_audit_log (
    organization_id, actor_id, event_type, invoice_id, details
  )
  VALUES (
    p_organization_id,
    p_actor_id,
    'InvoiceIssued',
    invoice.id,
    jsonb_build_object(
      'externalReference', invoice.external_reference,
      'amountCents', invoice.amount_cents,
      'currency', invoice.currency,
      'dueOn', invoice.due_on
    )
  );

  RETURN invoice;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_pro_payment_and_renewal(
  p_invoice_id uuid,
  p_actor_id uuid,
  p_paid_at timestamptz DEFAULT now()
)
RETURNS public.organization_commercial_accounts
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  invoice public.organization_invoices;
  account public.organization_commercial_accounts;
BEGIN
  SELECT * INTO invoice
  FROM public.organization_invoices
  WHERE id = p_invoice_id
  FOR UPDATE;

  IF invoice.id IS NULL THEN
    RAISE EXCEPTION 'invoice_not_found';
  END IF;
  IF invoice.status = 'Paid' THEN
    RAISE EXCEPTION 'invoice_already_paid';
  END IF;
  IF invoice.status NOT IN ('Issued', 'Overdue') THEN
    RAISE EXCEPTION 'invoice_not_payable';
  END IF;

  UPDATE public.organization_invoices
  SET
    status = 'Paid',
    paid_at = p_paid_at,
    payment_recorded_by = p_actor_id,
    updated_at = now()
  WHERE id = invoice.id;

  UPDATE public.organization_commercial_accounts
  SET
    status = 'Active',
    current_period_start = invoice.period_start,
    current_period_end = invoice.period_end,
    next_renewal_date = invoice.period_end,
    activated_at = COALESCE(activated_at, p_paid_at),
    updated_at = now()
  WHERE id = invoice.commercial_account_id
  RETURNING * INTO account;

  INSERT INTO public.organization_commercial_audit_log (
    organization_id, actor_id, event_type, invoice_id, details
  )
  VALUES
    (
      account.organization_id,
      p_actor_id,
      'PaymentRecorded',
      invoice.id,
      jsonb_build_object('paidAt', p_paid_at)
    ),
    (
      account.organization_id,
      p_actor_id,
      'ContractRenewed',
      invoice.id,
      jsonb_build_object(
        'periodStart', invoice.period_start,
        'periodEnd', invoice.period_end,
        'nextRenewalDate', invoice.period_end
      )
    );

  RETURN account;
END;
$$;

REVOKE ALL ON FUNCTION public.submit_pro_billing_profile(uuid, uuid, text, text, text, text)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.issue_pro_invoice(uuid, uuid, text, bigint, text, date, date, date, date)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.record_pro_payment_and_renewal(uuid, uuid, timestamptz)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.submit_pro_billing_profile(uuid, uuid, text, text, text, text)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.issue_pro_invoice(uuid, uuid, text, bigint, text, date, date, date, date)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.record_pro_payment_and_renewal(uuid, uuid, timestamptz)
  TO service_role;

REVOKE INSERT, UPDATE, DELETE ON public.organization_commercial_accounts
  FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.organization_invoices
  FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.organization_commercial_audit_log
  FROM anon, authenticated;
