-- O42 / M15: reversible, audited organization suspension with coherent access revocation.

ALTER TABLE public.organization_commercial_accounts
  ADD COLUMN suspension_reason text,
  ADD COLUMN suspended_at timestamptz,
  ADD COLUMN suspended_by uuid REFERENCES auth.users(id),
  ADD COLUMN reactivated_at timestamptz,
  ADD COLUMN reactivated_by uuid REFERENCES auth.users(id);

ALTER TABLE public.organization_commercial_audit_log
  DROP CONSTRAINT IF EXISTS organization_commercial_audit_log_event_type_check;
ALTER TABLE public.organization_commercial_audit_log
  ADD CONSTRAINT organization_commercial_audit_log_event_type_check CHECK (
    event_type IN (
      'BillingProfileSubmitted',
      'InvoiceIssued',
      'PaymentRecorded',
      'ContractRenewed',
      'OrganizationSuspended',
      'OrganizationReactivated'
    )
  );

CREATE TABLE public.organization_access_suspensions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  commercial_account_id uuid NOT NULL REFERENCES public.organization_commercial_accounts(id) ON DELETE RESTRICT,
  previous_commercial_status text NOT NULL CHECK (
    previous_commercial_status IN ('PendingActivation', 'AwaitingPayment', 'Active', 'PastDue')
  ),
  reason text NOT NULL,
  suspended_by uuid NOT NULL REFERENCES auth.users(id),
  suspended_at timestamptz NOT NULL DEFAULT now(),
  reactivated_by uuid REFERENCES auth.users(id),
  reactivated_at timestamptz
);

CREATE UNIQUE INDEX idx_one_open_organization_suspension
  ON public.organization_access_suspensions(organization_id)
  WHERE reactivated_at IS NULL;

CREATE TABLE public.organization_suspended_memberships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suspension_id uuid NOT NULL REFERENCES public.organization_access_suspensions(id) ON DELETE CASCADE,
  member_id uuid REFERENCES public.organization_members(id) ON DELETE SET NULL,
  UNIQUE (suspension_id, member_id)
);

CREATE TABLE public.organization_suspended_api_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suspension_id uuid NOT NULL REFERENCES public.organization_access_suspensions(id) ON DELETE CASCADE,
  api_key_id uuid REFERENCES public.api_keys(id) ON DELETE SET NULL,
  UNIQUE (suspension_id, api_key_id)
);

ALTER TABLE public.organization_access_suspensions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_suspended_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_suspended_api_keys ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.organization_access_suspensions FROM anon, authenticated;
REVOKE ALL ON public.organization_suspended_memberships FROM anon, authenticated;
REVOKE ALL ON public.organization_suspended_api_keys FROM anon, authenticated;

CREATE OR REPLACE FUNCTION private.is_organization_access_enabled(p_organization_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $function$
  SELECT NOT EXISTS (
    SELECT 1
    FROM public.organization_commercial_accounts account
    WHERE account.organization_id = p_organization_id
      AND account.status IN ('Suspended', 'Cancelled')
  );
$function$;

CREATE OR REPLACE FUNCTION private.is_organization_owner(
  p_organization_id uuid,
  p_user_id uuid DEFAULT auth.uid()
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $function$
  SELECT private.is_organization_access_enabled(p_organization_id)
    AND EXISTS (
      SELECT 1
      FROM public.organizations o
      WHERE o.id = p_organization_id
        AND o.owner_id = p_user_id
    );
$function$;

CREATE OR REPLACE FUNCTION private.is_active_organization_member(
  p_organization_id uuid,
  p_user_id uuid DEFAULT auth.uid()
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $function$
  SELECT private.is_organization_access_enabled(p_organization_id)
    AND EXISTS (
      SELECT 1
      FROM public.organization_members om
      WHERE om.organization_id = p_organization_id
        AND om.user_id = p_user_id
        AND om.status = 'Active'
    );
$function$;

REVOKE ALL ON FUNCTION private.is_organization_access_enabled(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION private.is_organization_access_enabled(uuid) TO authenticated;

DROP POLICY IF EXISTS "Users can view their API keys" ON public.api_keys;
CREATE POLICY "Users can view their API keys" ON public.api_keys
  FOR SELECT TO authenticated
  USING (
    user_id = auth.uid()
    AND (
      organization_id IS NULL
      OR private.is_organization_access_enabled(organization_id)
    )
  );

DROP POLICY IF EXISTS "Users can create their API keys" ON public.api_keys;
CREATE POLICY "Users can create their API keys" ON public.api_keys
  FOR INSERT TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND (
      organization_id IS NULL
      OR private.is_organization_access_enabled(organization_id)
    )
  );

DROP POLICY IF EXISTS "Users can update their API keys" ON public.api_keys;
CREATE POLICY "Users can update their API keys" ON public.api_keys
  FOR UPDATE TO authenticated
  USING (
    user_id = auth.uid()
    AND (
      organization_id IS NULL
      OR private.is_organization_access_enabled(organization_id)
    )
  )
  WITH CHECK (
    user_id = auth.uid()
    AND (
      organization_id IS NULL
      OR private.is_organization_access_enabled(organization_id)
    )
  );

DROP POLICY IF EXISTS "Users can delete their API keys" ON public.api_keys;
CREATE POLICY "Users can delete their API keys" ON public.api_keys
  FOR DELETE TO authenticated
  USING (
    user_id = auth.uid()
    AND (
      organization_id IS NULL
      OR private.is_organization_access_enabled(organization_id)
    )
  );

CREATE OR REPLACE FUNCTION public.suspend_pro_organization(
  p_organization_id uuid,
  p_actor_id uuid,
  p_reason text
)
RETURNS public.organization_commercial_accounts
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  account public.organization_commercial_accounts;
  suspension public.organization_access_suspensions;
BEGIN
  IF NULLIF(btrim(p_reason), '') IS NULL THEN
    RAISE EXCEPTION 'suspension_reason_required';
  END IF;

  SELECT * INTO account
  FROM public.organization_commercial_accounts
  WHERE organization_id = p_organization_id
  FOR UPDATE;

  IF account.id IS NULL THEN
    RAISE EXCEPTION 'commercial_account_not_found';
  END IF;
  IF account.status = 'Suspended' THEN
    RAISE EXCEPTION 'organization_already_suspended';
  END IF;
  IF account.status = 'Cancelled' THEN
    RAISE EXCEPTION 'cancelled_organization_cannot_be_suspended';
  END IF;

  INSERT INTO public.organization_access_suspensions (
    organization_id,
    commercial_account_id,
    previous_commercial_status,
    reason,
    suspended_by
  )
  VALUES (
    p_organization_id,
    account.id,
    account.status,
    btrim(p_reason),
    p_actor_id
  )
  RETURNING * INTO suspension;

  INSERT INTO public.organization_suspended_memberships (suspension_id, member_id)
  SELECT suspension.id, id
  FROM public.organization_members
  WHERE organization_id = p_organization_id
    AND status = 'Active';

  UPDATE public.organization_members
  SET status = 'Suspended', updated_at = now()
  WHERE organization_id = p_organization_id
    AND status = 'Active';

  INSERT INTO public.organization_suspended_api_keys (suspension_id, api_key_id)
  SELECT suspension.id, id
  FROM public.api_keys
  WHERE organization_id = p_organization_id
    AND is_active = true;

  UPDATE public.api_keys
  SET is_active = false, updated_at = now()
  WHERE organization_id = p_organization_id
    AND is_active = true;

  UPDATE public.organization_commercial_accounts
  SET
    status = 'Suspended',
    suspension_reason = btrim(p_reason),
    suspended_at = suspension.suspended_at,
    suspended_by = p_actor_id,
    reactivated_at = NULL,
    reactivated_by = NULL,
    updated_at = now()
  WHERE id = account.id
  RETURNING * INTO account;

  INSERT INTO public.organization_commercial_audit_log (
    organization_id, actor_id, event_type, details
  )
  VALUES (
    p_organization_id,
    p_actor_id,
    'OrganizationSuspended',
    jsonb_build_object(
      'suspensionId', suspension.id,
      'reason', suspension.reason,
      'previousStatus', suspension.previous_commercial_status
    )
  );

  RETURN account;
END;
$$;

CREATE OR REPLACE FUNCTION public.reactivate_pro_organization(
  p_organization_id uuid,
  p_actor_id uuid
)
RETURNS public.organization_commercial_accounts
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  account public.organization_commercial_accounts;
  suspension public.organization_access_suspensions;
BEGIN
  SELECT * INTO account
  FROM public.organization_commercial_accounts
  WHERE organization_id = p_organization_id
  FOR UPDATE;

  IF account.id IS NULL OR account.status <> 'Suspended' THEN
    RAISE EXCEPTION 'organization_not_suspended';
  END IF;

  SELECT * INTO suspension
  FROM public.organization_access_suspensions
  WHERE organization_id = p_organization_id
    AND reactivated_at IS NULL
  FOR UPDATE;

  IF suspension.id IS NULL THEN
    RAISE EXCEPTION 'open_suspension_not_found';
  END IF;

  UPDATE public.organization_members member
  SET status = 'Active', updated_at = now()
  FROM public.organization_suspended_memberships snapshot
  WHERE snapshot.suspension_id = suspension.id
    AND snapshot.member_id = member.id
    AND member.status = 'Suspended';

  UPDATE public.api_keys key
  SET is_active = true, updated_at = now()
  FROM public.organization_suspended_api_keys snapshot
  WHERE snapshot.suspension_id = suspension.id
    AND snapshot.api_key_id = key.id
    AND key.is_active = false;

  UPDATE public.organization_access_suspensions
  SET reactivated_by = p_actor_id, reactivated_at = now()
  WHERE id = suspension.id;

  UPDATE public.organization_commercial_accounts
  SET
    status = suspension.previous_commercial_status,
    suspension_reason = NULL,
    reactivated_at = now(),
    reactivated_by = p_actor_id,
    updated_at = now()
  WHERE id = account.id
  RETURNING * INTO account;

  INSERT INTO public.organization_commercial_audit_log (
    organization_id, actor_id, event_type, details
  )
  VALUES (
    p_organization_id,
    p_actor_id,
    'OrganizationReactivated',
    jsonb_build_object(
      'suspensionId', suspension.id,
      'restoredStatus', suspension.previous_commercial_status
    )
  );

  RETURN account;
END;
$$;

REVOKE ALL ON FUNCTION public.suspend_pro_organization(uuid, uuid, text)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.reactivate_pro_organization(uuid, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.suspend_pro_organization(uuid, uuid, text)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.reactivate_pro_organization(uuid, uuid)
  TO service_role;
