-- garden_tasks_task_type_check only allowed 11 legacy values, but GardenTask['taskType']
-- in types.ts has long included many more (Photo, Irrigation, hydroponic/aquaponic/aeroponic
-- maintenance types, extended pruning/tillage types, etc.) that production services already
-- insert (services/plantHealthMonitoringService.ts, services/weatherAwareTaskScheduler.ts).
-- Any insert using one of those values 400s against this stale constraint.
ALTER TABLE public.garden_tasks
  DROP CONSTRAINT IF EXISTS garden_tasks_task_type_check;

ALTER TABLE public.garden_tasks
  ADD CONSTRAINT garden_tasks_task_type_check
  CHECK (task_type IN (
    'Sowing',
    'Transplant',
    'Fertilize',
    'Prune',
    'Harvest',
    'Treatment',
    'Irrigation',
    'Photo',
    'Plowing',
    'Subsoiling',
    'Harrowing',
    'Tilling',
    'Rolling',
    'Hoeing',
    'EarthingUp',
    'Mulching',
    'PostSowingRolling',
    'Clearing',
    'Stumping',
    'StoneRemoval',
    'Leveling',
    'DeepSubsoiling',
    'Digging',
    'DeepHarrowing',
    'Crumbling',
    'Scraping',
    'SurfaceLeveling',
    'MinimumTillage',
    'StripTillage',
    'NoTill',
    'FormativePruning',
    'MaintenancePruning',
    'RejuvenationPruning',
    'SummerPruning',
    'WinterPruning',
    'Thinning',
    'Suckering',
    'Defoliation',
    'Tying',
    'OliveShredding',
    'RunnerManagement',
    'StrawberryMulching',
    'StrawberryCleaning',
    'CaneRemoval',
    'TipPruning',
    'RaspberryTying',
    'SuckerThinning',
    'FruitBagging',
    'ExoticThinning',
    'Shredding',
    'Topping',
    'Pruning',
    'TreePruning',
    'HydroNutrientCheck',
    'HydroSolutionChange',
    'HydroSystemClean',
    'HydroPhAdjust',
    'HydroEcAdjust',
    'HydroAlgaeControl',
    'HydroEquipmentCheck',
    'AquaponicFishFeed',
    'AquaponicWaterTest',
    'AquaponicFilterClean',
    'AeroponicNozzleClean',
    'AeroponicPressureCheck'
  ));
